"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

export type Language = "th" | "en"

interface LanguageContextType {
  lang: Language
  setLang: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  th: {
    // Header & Global
    "portal.title": "ADMIN PORTAL",
    "portal.subtitle": "ระบบบริหารจัดการกลาง",
    "portal.system_online": "สถานะระบบ: พร้อมใช้งาน (Online)",
    "nav.home": "หน้าหลัก",
    "nav.admin": "ระบบผู้ดูแลระบบ (Admin)",
    "nav.dashboard": "แดชบอร์ดภาพรวม (Dashboard)",
    "nav.settings": "การตั้งค่า",
    "nav.profile": "การตั้งค่า",
    "nav.privacy": "นโยบายความเป็นส่วนตัว",
    "nav.signout": "ออกจากระบบ (Sign Out)",
    "role.admin": "เจ้าหน้าที่ดูแลระบบ (Admin)",
    "role.photographer": "ช่างภาพ (Photographer)",
    "role.student": "นักศึกษา (Student)",
    "role.super_admin": "ผู้ดูแลระบบระดับสูง (Super Admin)",

    // Breadcrumbs
    "breadcrumb.home": "หน้าหลัก",
    "breadcrumb.admin": "ระบบผู้ดูแลระบบ (Admin)",
    "breadcrumb.dashboard": "แดชบอร์ดภาพรวม (Dashboard)",
    "breadcrumb.create_event": "สร้างกิจกรรมใหม่ (Create Event)",
    "breadcrumb.edit_event": "แก้ไขกิจกรรม (Edit Event)",
    "breadcrumb.profile": "การตั้งค่า (Settings)",
    "breadcrumb.settings": "การตั้งค่า (Settings)",
    "breadcrumb.back": "กลับหน้าหลัก",

    // Navigation Extras
    "nav.my_photos": "ภาพถ่ายของฉัน",
    "nav.favorites": "ภาพที่บันทึกไว้",
    "student.space": "พื้นที่นักศึกษา",
    "student.welcome": "ยินดีต้อนรับกลับ,",
    "student.description": "พื้นที่รูปภาพกิจกรรมส่วนตัวของคุณ ตั้งค่าโปรไฟล์ครั้งเดียว แล้วให้ Photo Finder นำช่วงเวลาของคุณมาให้",
    "student.profile_signal": "สถานะโปรไฟล์",
    "student.active": "ใช้งานอยู่",
    "student.inactive": "ยังไม่ได้เปิดใช้งาน",
    "student.ready": "พร้อมค้นหา",
    "student.not_set_up": "ยังไม่ได้ตั้งค่า",
    "student.ready_description": "ระบบจะตรวจสอบรูปกิจกรรมใหม่ให้คุณโดยอัตโนมัติ",
    "student.not_set_up_description": "เพิ่มรูปเซลฟี่เพื่อเริ่มค้นหารูปกิจกรรมของคุณ",
    "student.auto_matches": "รูปที่จับคู่ได้",
    "student.saved_moments": "รูปที่บันทึกไว้",
    "student.profile_status": "สถานะโปรไฟล์",
    "student.update_profile": "อัปเดตโปรไฟล์",
    "student.set_selfie": "ตั้งค่ารูปเซลฟี่",
    "student.remove_profile": "ลบรูปโปรไฟล์",
    "student.remove_profile_confirm": "คุณแน่ใจหรือไม่ว่าต้องการลบรูปเซลฟี่โปรไฟล์ของคุณ?",
    "student.remove_profile_modal_title": "ยืนยันการลบรูปเซลฟี่โปรไฟล์",
    "student.remove_profile_modal_desc": "คุณแน่ใจหรือไม่ว่าต้องการลบรูปเซลฟี่อ้างอิงและข้อมูลเวกเตอร์ใบหน้าออกจากระบบ?",
    "student.remove_profile_consequence": "ระบบจะหยุดค้นหาและจับคู่รูปภาพในกิจกรรมให้คุณโดยอัตโนมัติ จนกว่าคุณจะลงทะเบียนรูปเซลฟี่ใหม่อีกครั้ง",
    "student.remove_profile_cancel": "ยกเลิก",
    "student.remove_profile_action": "ลบรูปโปรไฟล์",
    "student.remove_profile_deleting": "กำลังลบ...",
    "student.remove_profile_error": "ไม่สามารถลบรูปอ้างอิงได้",
    "student.network_error": "เกิดข้อผิดพลาดในการเชื่อมต่อ กรุณาลองใหม่อีกครั้ง",
    "student.browse_photos": "ดูรูปภาพ",
    "student.collection": "คอลเลกชันของคุณ",
    "student.recently_matched": "ช่วงเวลาพิเศษของคุณ",
    "student.no_matches": "ยังไม่พบรูปภาพที่ตรงกับคุณ",
    "student.no_matches_description": "ลองกลับมาตรวจสอบอีกครั้งหลังจบกิจกรรมครั้งถัดไป",
    "student.view_all": "ดูทั้งหมด",
    "student.settings_title": "การตั้งค่า (Settings)",
    "student.settings_subtitle": "จัดการข้อมูลบัญชี การแจ้งเตือน และความเป็นส่วนตัว (PDPA)",
    "student.account_section": "ข้อมูลบัญชีผู้ใช้ (Account Information)",
    "student.account_desc": "ข้อมูลบัญชีที่เข้าสู่ระบบผ่าน Google Workspace มหาวิทยาลัยแม่ฟ้าหลวง",
    "student.ref_face_title": "สถานะรูปภาพอ้างอิงใบหน้า",
    "student.ref_face_registered": "ลงทะเบียนใบหน้าแล้ว",
    "student.ref_face_unregistered": "ยังไม่ได้ลงทะเบียนใบหน้า",
    "student.ref_face_update": "อัปเดตรูปใบหน้า",
    "student.ref_face_set": "ลงทะเบียนใบหน้า",
    "student.notif_section": "ช่องทางการรับการแจ้งเตือน (Notification Channels)",
    "student.notif_desc": "รับการแจ้งเตือนทันทีเมื่อระบบ AI ตรวจพบภาพถ่ายของคุณในกิจกรรม",
    "student.line_title": "LINE Official Account",
    "student.line_desc": "รับข้อความแจ้งเตือนภาพถ่ายและพรีวิวรูปภาพผ่าน LINE",
    "student.line_connected": "เชื่อมต่อแล้ว",
    "student.line_not_connected": "ยังไม่ได้เชื่อมต่อ",
    "student.line_link_btn": "เชื่อมต่อ LINE",
    "student.line_unlink_btn": "ยกเลิกการเชื่อมต่อ",
    "student.line_add_friend": "เพิ่มเพื่อน LINE OA ก่อนเชื่อมต่อ: @042nimvi",
    "student.email_title": "การแจ้งเตือนทางอีเมล (Email Notification)",
    "student.email_desc": "ส่งอีเมลสรุปเมื่อมีภาพถ่ายกิจกรรมใหม่ของคุณ",
    "student.email_active": "เปิดใช้งาน",
    "student.email_inactive": "ปิดใช้งาน",
    "student.privacy_section": "ความเป็นส่วนตัวและข้อมูลส่วนบุคคล (Privacy & PDPA)",
    "student.privacy_desc": "กำหนดสิทธิ์การค้นหาใบหน้าและการประมวลผลข้อมูลชีวมิติตามกฎหมาย PDPA",
    "student.consent_face_title": "อนุญาตการค้นหาและจับคู่ใบหน้าอัตโนมัติ (AI Face Search)",
    "student.consent_face_desc": "อนุญาตให้ระบบ AI ค้นหาใบหน้าของคุณในภาพถ่ายกิจกรรม เพื่อนำมารวบรวมในพื้นที่รูปภาพของคุณ",
    "student.consent_data_title": "ยินยอมให้ประมวลผลข้อมูลชีวมิติ (Biometric Data Processing)",
    "student.consent_data_desc": "ยินยอมให้ระบบจัดเก็บและประมวลผลข้อมูลเวกเตอร์ใบหน้า (Facial Embeddings) ตามมาตรฐานความปลอดภัย",
    "student.rights_section": "สิทธิและการจัดการข้อมูลส่วนบุคคล (Data Subject Rights)",
    "student.rights_desc": "ท่านสามารถขอรับสำเนาข้อมูลหรือขอลบข้อมูลส่วนบุคคลทั้งหมดได้ตามสิทธิ PDPA",
    "student.btn_export": "ดาวน์โหลดข้อมูลส่วนบุคคล (Export Data)",
    "student.btn_export_desc": "ดาวน์โหลดสำเนาประวัติและข้อมูลส่วนบุคคลในรูปแบบ JSON",
    "student.btn_delete": "ลบข้อมูลส่วนบุคคลทั้งหมด (Delete All Data)",
    "student.btn_delete_desc": "ลบรูปเซลฟี่อ้างอิง เวกเตอร์ใบหน้า และข้อมูลที่บันทึกไว้ทั้งหมดอย่างถาวร",
    "student.btn_save": "บันทึกการตั้งค่า",
    "student.btn_saving": "กำลังบันทึก...",
    "student.save_success": "บันทึกการตั้งค่าเรียบร้อยแล้ว",
    "student.save_error": "บันทึกการตั้งค่าไม่สำเร็จ กรุณาลองใหม่อีกครั้ง",
    "student.withdraw_warning": "หากปิดการค้นหาใบหน้า ระบบจะไม่จับคู่หรือแจ้งเตือนภาพถ่ายกิจกรรมใหม่ของคุณโดยอัตโนมัติ",
    "student.withdraw_face_warning": "ปิดการค้นหาใบหน้าอัตโนมัติ: ระบบจะไม่จับคู่หรือแจ้งเตือนภาพถ่ายกิจกรรมใหม่ของคุณโดยอัตโนมัติ แต่ข้อมูลและรูปอ้างอิงของคุณยังคงปลอดภัยในระบบ",
    "student.withdraw_data_warning": "คำเตือน: หากปิดการยินยอมประมวลผลข้อมูลชีวมิติ (PDPA) ระบบจะลบรูปเซลฟี่อ้างอิงและระงับการทำงานของ AI ทั้งหมด",
    "student.consent_modal_title": "จำเป็นต้องให้ความยินยอม (Consent Required)",
    "student.consent_modal_desc": "กรุณาเปิดการยินยอมเหล่านี้ก่อนเริ่มใช้งานระบบค้นหาใบหน้า:",
    "student.consent_modal_face_title": "ค้นหาใบหน้าด้วย AI (AI Face Search)",
    "student.consent_modal_face_desc": "ค้นหาใบหน้าของคุณในภาพถ่ายกิจกรรม เพื่อรวบรวมรูปภาพของคุณ",
    "student.consent_modal_data_title": "ประมวลผลข้อมูลชีวมิติ (Data Processing)",
    "student.consent_modal_data_desc": "ข้อมูลชีวมิติของคุณจะได้รับการจัดเก็บและประมวลผลอย่างปลอดภัยตามมาตรฐาน PDPA",
    "student.consent_modal_dismiss": "ปิดหน้าต่าง",
    "student.consent_modal_settings": "ไปยังหน้าตั้งค่า",
    "student.updating_profile": "กำลังอัปเดตข้อมูลใบหน้าของคุณ...",
    "student.mapping_face": "กำลังวิเคราะห์และสร้างเวกเตอร์ใบหน้า...",
    "student.profile_title": "การตั้งค่า (Settings)",
    "student.profile_subtitle": "จัดการข้อมูลบัญชี การแจ้งเตือน และการยินยอมข้อมูลส่วนบุคคล (PDPA)",
    "student.profile_back": "กลับหน้าหลัก",
    "student.role_badge": "นักศึกษา (Student)",
    "student.metrics_title": "สถิติและสถานะบัญชี (Account Statistics)",
    "student.stat_matches": "รูปที่จับคู่ได้",
    "student.stat_saved": "รูปที่บันทึกไว้",
    "student.stat_face": "สถานะใบหน้าอ้างอิง",
    "student.stat_notifications": "การแจ้งเตือน",
    "student.face_ready": "พร้อมใช้งาน",
    "student.face_none": "ยังไม่ตั้งค่า",
    "student.notifications_title": "ช่องทางการรับการแจ้งเตือน (Notification Channels)",
    "student.notifications_desc": "กำหนดช่องทางรับการแจ้งเตือนเมื่อระบบ AI ตรวจพบภาพถ่ายของคุณในกิจกรรม",
    "student.privacy_title": "การยินยอมและความเป็นส่วนตัว (Privacy & PDPA Consent)",
    "nav.student_profile": "การตั้งค่า",
    "favorites.space": "พื้นที่รูปภาพของคุณ",
    "favorites.title": "รายการโปรด",
    "favorites.description": "รวมรูปกิจกรรมที่คุณบันทึกไว้ในที่เดียว",
    "favorites.count": "รูปที่บันทึกไว้",
    "favorites.collection": "คอลเลกชันของคุณ",
    "favorites.saved_collection": "รูปที่บันทึกไว้",
    "favorites.loading": "กำลังโหลดรูปที่บันทึกไว้...",
    "favorites.error": "ไม่สามารถโหลดรายการโปรดได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง",
    "favorites.empty": "ยังไม่มีรูปที่บันทึกไว้",
    "favorites.empty_description": "กดไอคอนหัวใจบนรูปที่คุณชอบเพื่อบันทึกไว้ที่นี่",
    "search.space": "คลังรูปภาพ",
    "search.title": "ดูรูปภาพ",
    "search.description": "ค้นหารูปภาพจากกิจกรรมในมหาวิทยาลัย",
    "search.count": "รูปภาพ",
    "search.loading": "กำลังโหลดรูปภาพ...",
    "search.error": "ไม่สามารถโหลดรูปภาพได้",
    "search.empty": "ยังไม่มีรูปภาพ",

    // Dashboard Banner & Metrics
    "dash.title": "แดชบอร์ดผู้ดูแลระบบ (Admin Dashboard)",
    "dash.welcome": "ระบบบริหารจัดการข้อมูลกลาง | ยินดีต้อนรับ,",
    "dash.btn.create_event": "สร้างกิจกรรมใหม่",
    "dash.btn.settings": "ตั้งค่าระบบ",
    "dash.metric.active_events": "กิจกรรมที่เปิดใช้งาน (Active)",
    "dash.metric.total_events": "กิจกรรมทั้งหมด (Total Events)",
    "dash.metric.pending_requests": "คำร้องขอลบภาพ (Pending Requests)",
    "dash.metric.total_users": "ผู้ใช้งานในระบบ (Total Users)",
    "dash.metric.out_of": "จากทั้งหมด",
    "dash.metric.events_unit": "กิจกรรม",
    "dash.metric.in_db": "สะสมในฐานข้อมูล",
    "dash.metric.awaiting_review": "รอการตรวจสอบและดำเนินการ",
    "dash.metric.all_roles": "รวมทุกสิทธิ์การใช้งาน",

    // Dashboard Menu
    "menu.title": "เมนูหลัก (Main Menu)",
    "menu.events": "จัดการกิจกรรม (Events)",
    "menu.photos": "คลังภาพถ่าย (Photos)",
    "menu.low_confidence": "คิวตรวจสอบ AI (Review)",
    "menu.requests": "คำร้องขอลบภาพ (Requests)",
    "menu.users": "จัดการผู้ใช้งาน (Users)",
    "menu.health": "สถานะระบบ (System Health)",
    "menu.audit_logs": "บันทึกการตรวจสอบ (Audit Logs)",

    // Audit Logs Tab
    "audit.title": "บันทึกการตรวจสอบความปลอดภัยและ PDPA (Audit Logs)",
    "audit.desc": "ตรวจสอบประวัติการดำเนินงานของผู้ดูแลระบบ การจัดการสิทธิ และข้อมูลชีวมิติ",
    "audit.retention_notice": "นโยบายการเก็บรักษาข้อมูล (PDPA 90 วัน): บันทึกการตรวจสอบจะถูกเก็บรักษาไว้เป็นเวลา 90 วันเพื่อความโปร่งใสทางกฎหมายและความปลอดภัย โดยระบบจะล้างข้อมูลที่เกินกำหนดโดยอัตโนมัติทุกเที่ยงคืน",
    "audit.search_placeholder": "ค้นหาด้วยอีเมลผู้ทำรายการ, เป้าหมาย, หรือการกระทำ...",
    "audit.export_csv": "ส่งออก CSV",
    "audit.category_all": "ทั้งหมด (All Categories)",
    "audit.category_biometrics": "ข้อมูลชีวมิติ (Biometrics)",
    "audit.category_users": "จัดการผู้ใช้ (User Mgmt)",
    "audit.category_content": "เนื้อหาและภาพถ่าย (Content)",
    "audit.category_security": "ความปลอดภัย (Security)",
    "audit.col_time": "เวลา (Timestamp)",
    "audit.col_actor": "ผู้ดำเนินการ (Actor)",
    "audit.col_action": "การกระทำ (Action)",
    "audit.col_target": "เป้าหมาย (Target)",
    "audit.col_details": "รายละเอียด (Details)",
    "audit.empty": "ไม่พบบันทึกการตรวจสอบตามเงื่อนไขที่ระบุ",

    // Events Tab
    "events.title": "รายการกิจกรรมทั้งหมด (Events List)",
    "events.desc": "จัดการกิจกรรม ค้นหา และตรวจสอบสถานะการเผยแพร่",
    "events.search_placeholder": "ค้นหาชื่อกิจกรรม...",
    "events.create_btn": "สร้าง",
    "events.loading": "กำลังโหลดข้อมูลกิจกรรม...",
    "events.not_found": "ไม่พบข้อมูลกิจกรรม",
    "events.not_found_desc": "ลองเปลี่ยนคำค้นหา หรือสร้างกิจกรรมใหม่",
    "events.col.name": "ชื่อกิจกรรม (Event Name)",
    "events.col.date": "วันที่จัดกิจกรรม",
    "events.col.created": "วันที่สร้าง",
    "events.col.status": "สถานะ",
    "events.col.actions": "การจัดการ",
    "events.status.published": "เผยแพร่แล้ว",
    "events.status.draft": "ฉบับร่าง",
    "events.status.archived": "จัดเก็บแล้ว",
    "events.btn.edit": "แก้ไข",
    "events.btn.delete": "ลบ",

    // Photos Tab
    "photos.title": "คลังภาพถ่ายทั้งหมด (Photos Catalog)",
    "photos.desc": "ภาพถ่ายที่อัปโหลดเข้าสู่ระบบทั้งหมด",
    "photos.search_placeholder": "ค้นหาตามชื่อกิจกรรม หรือชื่อไฟล์...",
    "photos.loading": "กำลังโหลดข้อมูลภาพถ่าย...",
    "photos.not_found": "ไม่พบภาพถ่ายในระบบ",
    "photos.not_found_desc": "ภาพถ่ายที่อัปโหลดจะปรากฏที่นี่",
    "photos.items_count": "รูป",

    // Low Confidence Queue Tab
    "lc.title": "คิวตรวจสอบภาพถ่าย AI (Low-Confidence Queue)",
    "lc.desc": "ตรวจสอบภาพถ่ายที่ค่าความแม่นยำใบหน้าต่ำกว่าเกณฑ์มาตรฐาน",
    "lc.search_placeholder": "ค้นหาชื่อกิจกรรม...",
    "lc.threshold": "เกณฑ์ (Threshold):",
    "lc.refresh": "รีเฟรช",
    "lc.refreshing": "กำลังโหลด...",
    "lc.loading": "กำลังโหลดคิวตรวจสอบ...",
    "lc.clear": "ไม่มีภาพถ่ายในคิวตรวจสอบ",
    "lc.clear_desc": "ภาพถ่ายทั้งหมดผ่านเกณฑ์ความเชื่อมั่นที่กำหนด",
    "lc.min_confidence": "ค่าความเชื่อมั่นต่ำสุด:",
    "lc.lc_faces": "ใบหน้าต่ำกว่าเกณฑ์:",
    "lc.total_faces": "ใบหน้าทั้งหมด:",
    "lc.btn.review": "ตรวจสอบภาพ",
    "lc.modal.title": "ตรวจสอบภาพถ่ายค่าความเชื่อมั่นต่ำ",
    "lc.modal.preview_btn": "เปิดรูปเต็ม (Preview)",
    "lc.modal.approve_btn": "อนุมัติภาพ (Approve)",
    "lc.modal.approving": "กำลังอนุมัติ...",
    "lc.modal.delete_btn": "ลบภาพ (Delete)",
    "lc.modal.goto_event": "ไปที่แก้ไขกิจกรรม",

    // Removal Requests Tab
    "req.title": "คำร้องขอลบหรือเบลอภาพถ่าย (Removal Requests)",
    "req.desc": "ตรวจสอบคำร้องขอจากผู้ใช้งานเพื่อสิทธิความเป็นส่วนตัว",
    "req.loading": "กำลังโหลดคำร้อง...",
    "req.clear": "ไม่มีคำร้องขอลบภาพค้างอยู่",
    "req.clear_desc": "เมื่อมีผู้ใช้ส่งคำร้องขอ ระบบจะแสดงรายการในส่วนนี้",
    "req.requested_by": "ส่งคำร้องโดย",
    "req.on_date": "เมื่อ",
    "req.at_time": "เวลา",
    "req.reason_label": "เหตุผลที่ขอจัดการ:",
    "req.btn.approve_delete": "อนุมัติและลบภาพ",
    "req.btn.approve_blur": "อนุมัติและเบลอใบหน้า",
    "req.btn.reject": "ปฏิเสธคำร้อง",
    "req.processing": "กำลังดำเนินการ...",

    // User Management Tab
    "users.title": "รายชื่อผู้ใช้งานทั้งหมด (User Management)",
    "users.desc": "รวมทุกบัญชีผู้ใช้งานในระบบ",
    "users.add_photographer.title": "เพิ่มช่างภาพ (Add Photographer)",
    "users.add_photographer.desc": "กรอกอีเมล Google หรือ MFU ของช่างภาพ เมื่อเข้าสู่ระบบระบบจะนำทางไปยังหน้าจัดการของช่างภาพโดยอัตโนมัติ",
    "users.add_photographer.placeholder": "photographer@gmail.com หรือ photographer@mfu.ac.th",
    "users.add_photographer.btn": "แต่งตั้งช่างภาพ",
    "users.add_admin.title": "แต่งตั้งผู้ดูแลระบบ (Add Admin)",
    "users.add_admin.desc": "เฉพาะผู้ดูแลระบบระดับสูง (Super Admin) เท่านั้นที่สามารถแต่งตั้งหรือถอดถอนผู้ดูแลระบบคนอื่นได้",
    "users.add_admin.placeholder": "admin@gmail.com",
    "users.add_admin.btn": "แต่งตั้ง Admin",
    "users.search_placeholder": "ค้นหาชื่อ หรืออีเมล...",
    "users.col.details": "ข้อมูลผู้ใช้งาน (User Details)",
    "users.col.status": "สถานะ (Status)",
    "users.col.role": "สิทธิ์ (Role)",
    "users.col.actions": "การจัดการ (Actions)",
    "users.status.active": "ปกติ (Active)",
    "users.status.blocked": "ระงับสิทธิ์ (Blocked)",
    "users.btn.block": "ระงับ",
    "users.btn.unblock": "เปิดสิทธิ์",
    "users.btn.demote": "ลดสิทธิ์",
    "users.btn.delete": "ลบ",
    "users.not_found": "ไม่พบรายชื่อผู้ใช้งาน",
    "users.not_found_desc": "กรุณาลองปรับเปลี่ยนคำค้นหา",

    // System Health & Danger Zone
    "health.title": "สถานะระบบและประสิทธิภาพ (System Health)",
    "health.desc": "การตรวจสอบเมตริกและประสิทธิภาพการทำงานแบบเรียลไทม์",
    "health.total_users": "ผู้ใช้งานทั้งหมด",
    "health.total_events": "กิจกรรมทั้งหมด",
    "health.total_photos": "ภาพถ่ายทั้งหมด",
    "health.faces_detected": "ใบหน้าที่ตรวจพบ",
    "health.active_events": "กิจกรรมที่เปิดใช้งาน",
    "health.ai_confidence": "ความเชื่อมั่นโมเดล AI (AI Confidence)",
    "health.ai_confidence_desc": "ค่าความแม่นยำเฉลี่ยของการตรวจจับและจับคู่ใบหน้า",
    "health.events_by_status": "สัดส่วนสถานะกิจกรรม (Events by Status)",
    "health.events_status_desc": "การกระจายตัวของสถานะกิจกรรม",
    "health.photos_by_status": "สัดส่วนสถานะภาพถ่าย (Photos by Status)",
    "health.photos_status_desc": "รายละเอียดขั้นตอนการประมวลผลภาพถ่าย",
    "health.users_by_role": "สัดส่วนสิทธิ์ผู้ใช้งาน (Users by Role)",
    "health.users_role_desc": "การกระจายตัวของสิทธิ์บัญชีผู้ใช้",
    "health.danger.title": "พื้นที่อันตราย (Danger Zone)",
    "health.danger.desc": "การดำเนินการในส่วนนี้จะมีผลลบหรือเปลี่ยนแปลงข้อมูลขนาดใหญ่โดยถาวร",
    "health.danger.wipe_title": "ล้างรูปภาพโปรไฟล์ยืนยันตัวตนเก่าทั้งหมด (Wipe All Old Selfies)",
    "health.danger.wipe_desc": "บังคับให้นักศึกษาทุกคนต้องทำการยืนยันตัวตนใหม่ด้วยระบบ Identity Guard",
    "health.danger.wipe_btn": "ล้างและรีเซ็ตข้อมูลรูปโปรไฟล์",

    // Event Create & Edit
    "event_form.create_title": "สร้างกิจกรรมใหม่ (Create New Event)",
    "event_form.create_subtitle": "กำหนดข้อมูลกิจกรรมสำหรับเปิดให้ช่างภาพอัปโหลดภาพถ่ายและเปิดระบบค้นหาใบหน้านักศึกษา",
    "event_form.edit_title": "แก้ไขข้อมูลกิจกรรม (Edit Event)",
    "event_form.edit_subtitle": "ปรับปรุงชื่อกิจกรรม วันที่จัด หรือสถานะการเผยแพร่ของกิจกรรม",
    "event_form.card_title": "ข้อมูลรายละเอียดกิจกรรม (Event Details)",
    "event_form.card_desc": "กรุณากรอกข้อมูลให้ครบถ้วนเพื่อดำเนินการในระบบ",
    "event_form.name_label": "ชื่อกิจกรรม (Event Name)",
    "event_form.name_placeholder": "เช่น พิธีพระราชทานปริญญาบัตร ประจำปีการศึกษา 2568",
    "event_form.name_help": "ระบุชื่อกิจกรรมภาษาไทยหรือภาษาอังกฤษให้ชัดเจน",
    "event_form.date_label": "วันที่จัดกิจกรรม (Event Date)",
    "event_form.date_help": "วันที่จัดกิจกรรมตามปฏิทินของมหาวิทยาลัย",
    "event_form.status_label": "สถานะการเผยแพร่ (Event Status)",
    "event_form.status_draft": "ฉบับร่าง (Draft) - ซ่อนจากผู้ใช้",
    "event_form.status_published": "เผยแพร่แล้ว (Published) - แสดงให้ผู้ใช้เห็น",
    "event_form.status_archived": "จัดเก็บแล้ว (Archived) - ปิดการใช้งาน",
    "event_form.timer_label": "ระยะเวลาเก็บรักษาภาพถ่าย (Auto-Deletion Timer)",
    "event_form.timer_desc": "ตามนโยบายคุ้มครองข้อมูลส่วนบุคคล (PDPA) ภาพถ่ายและข้อมูลใบหน้าจะถูกลบอัตโนมัติหลังครบกำหนดเวลา",
    "event_form.days_unit": "วัน",
    "event_form.custom_days": "กำหนดเอง (วัน):",
    "event_form.max_days": "(สูงสุดไม่เกิน 30 วัน)",
    "event_form.btn_cancel": "ยกเลิก (Cancel)",
    "event_form.btn_create": "บันทึกและสร้างกิจกรรม",
    "event_form.btn_save": "บันทึกการเปลี่ยนแปลง",
    "event_form.btn_saving": "กำลังบันทึกข้อมูล...",
    "event_form.back": "กลับหน้าหลัก",
    "event_form.next_steps_title": "ขั้นตอนหลังจากสร้างกิจกรรม:",
    "event_form.next_step1": "กิจกรรมจะแสดงในแผงควบคุมระบบของผู้ดูแลระบบและช่างภาพ",
    "event_form.next_step2": "ช่างภาพที่ได้รับสิทธิ์สามารถเริ่มอัปโหลดภาพถ่ายเข้าระบบได้ทันที",
    "event_form.next_step3": "ระบบ AI จะประมวลผลและสร้าง Face Embedding เพื่อให้นักศึกษาค้นหาใบหน้าตนเอง",

    // Profile & Settings
    "profile.title": "ข้อมูลบัญชีผู้ดูแลระบบ (Admin Account & Profile)",
    "profile.subtitle": "รายละเอียดบัญชีและสิทธิ์การเข้าถึงระบบบริหารจัดการส่วนกลาง",
    "profile.details_title": "ข้อมูลส่วนบุคคล (Personal Details)",
    "profile.details_desc": "ข้อมูลเชื่อมโยงจากบัญชีเข้าสู่ระบบปัจจุบัน",
    "profile.scope_title": "ขอบเขตสิทธิ์การใช้งาน (Permission Scope)",
    "profile.btn_dashboard": "ไปยังแดชบอร์ดหลัก",
    "profile.email_not_found": "ไม่พบข้อมูลอีเมล",
    "profile.scope_desc_super": "คุณมีสิทธิ์ระดับสูงสุด สามารถจัดการผู้ดูแลระบบ (Admin), ช่างภาพ (Photographer), จัดการกิจกรรม, อนุมัติลบภาพ และตรวจสอบสถานะระบบทั้งหมดได้",
    "profile.scope_desc_admin": "คุณมีสิทธิ์ระดับผู้ดูแลระบบ สามารถจัดการกิจกรรม, อนุมัติลบหรือเบลอภาพถ่าย, และตรวจสอบคิว Low Confidence ได้",
    "settings.title": "การตั้งค่าระบบ (Admin Settings)",
    "settings.subtitle": "ตรวจสอบสิทธิ์การเข้าถึง และการกำหนดค่าระบบบริหารจัดการส่วนกลาง",
    "settings.session_title": "สถานะการเข้าถึงระบบของผู้ดูแล (Admin Session)",
    "settings.session_desc": "ข้อมูลเซสชันและสถานะการยืนยันตัวตนปัจจุบัน",
    "settings.signed_in_as": "เข้าสู่ระบบในนาม (Signed In As)",
    "settings.session_active": "เซสชันของผู้ดูแลระบบเปิดใช้งานและปลอดภัย",
    "settings.user_roles_title": "จัดการสิทธิ์ผู้ใช้งาน (User Roles)",
    "settings.user_roles_desc": "แต่งตั้งช่างภาพ ปรับระดับสิทธิ์ หรือระงับการเข้าถึงของผู้ใช้",
    "settings.moderation_title": "คำร้องขอลบภาพ (Moderation)",
    "settings.moderation_desc": "ตรวจสอบคำร้องขอลบหรือเบลอภาพถ่ายจากนักศึกษา",

    // User Settings & Privacy
    "user_settings.title": "การตั้งค่าบัญชีและข้อมูลส่วนตัว (Account & Settings)",
    "user_settings.subtitle": "จัดการข้อมูลโปรไฟล์ การแจ้งเตือน และการยินยอมข้อมูลส่วนบุคคล (PDPA)",
    "user_settings.tab_account": "ข้อมูลบัญชีผู้ใช้ (Account Profile)",
    "user_settings.tab_privacy": "การยินยอมและความเป็นส่วนตัว (Privacy & Consent)",
    "user_settings.profile_card_title": "ข้อมูลโปรไฟล์ (Account Profile)",
    "user_settings.profile_card_desc": "รายละเอียดข้อมูลบัญชีผู้ใช้ที่กำลังใช้งานในระบบ",
    "user_settings.full_name": "ชื่อ-นามสกุล (Full Name)",
    "user_settings.email": "อีเมล (Email Address)",
    "user_settings.role": "สิทธิ์การใช้งาน (Account Role)",
    "user_settings.sync_info": "ข้อมูลโปรไฟล์นี้เชื่อมโยงจากบัญชี Google ของท่าน หากต้องการอัปเดตรูปหรือชื่อ สามารถแก้ไขได้ที่บัญชี Google แล้วเข้าสู่ระบบใหม่เพื่อซิงค์ข้อมูล",
    "user_settings.line_title": "การแจ้งเตือนผ่าน LINE (LINE Notifications)",
    "user_settings.line_desc": "รับการแจ้งเตือนรูปถ่ายใหม่แบบทันทีผ่าน LINE Official Account เมื่อระบบ AI ตรวจพบภาพของคุณ",
    "user_settings.line_connected": "เชื่อมต่อแล้ว (Connected)",
    "user_settings.line_not_linked": "ยังไม่เชื่อมต่อ (Not Linked)",
    "user_settings.line_add_friend_title": "กรุณาเพิ่มเพื่อน LINE Official Account ก่อนเชื่อมต่อ",
    "user_settings.line_add_friend_desc": "เพิ่มเพื่อนผ่านลิงก์:",
    "user_settings.line_search_id": "หรือค้นหาไอดี:",
    "user_settings.line_oa_warning": "หากไม่เพิ่มเพื่อนก่อน ระบบจะไม่สามารถส่งข้อความแจ้งเตือนรูปถ่ายให้ท่านได้",
    "user_settings.line_btn_unlink": "ยกเลิกการเชื่อมต่อ (Unlink)",
    "user_settings.line_btn_link": "เชื่อมต่อบัญชี LINE",
    "user_settings.line_status_linked": "บัญชี LINE ของท่านเชื่อมต่อเรียบร้อยแล้ว ท่านจะได้รับการแจ้งเตือนอัตโนมัติเมื่อพบรูปถ่าย",
    "user_settings.email_title": "การแจ้งเตือนผ่านอีเมล (Email Notifications)",
    "user_settings.email_desc": "รับอีเมลสรุปภาพถ่ายกิจกรรมเมื่อระบบ AI ตรวจพบภาพของคุณในกิจกรรม",
    "user_settings.email_enabled": "เปิดใช้งานแล้ว (Enabled)",
    "user_settings.email_disabled": "ปิดการใช้งาน (Disabled)",
    "user_settings.email_btn_enable": "เปิดรับการแจ้งเตือนทางอีเมล",
    "user_settings.email_btn_disable": "ปิดรับการแจ้งเตือนทางอีเมล",
    "user_settings.consent_card_title": "สถานะการยินยอมข้อมูล (Consent Status)",
    "user_settings.consent_card_desc": "จัดการการมีส่วนร่วมในระบบค้นหาใบหน้าและประมวลผลข้อมูล",
    "user_settings.consent_opted_in": "ยินยอมใช้งาน (Opted In)",
    "user_settings.consent_opted_out": "ยกเลิกการยินยอม (Opted Out)",
    "user_settings.consent_active_desc": "ระบบกำลังประมวลผลตรวจจับใบหน้าของคุณในภาพกิจกรรมใหม่ และจะแจ้งเตือนอัตโนมัติเมื่อพบภาพถ่ายของคุณ",
    "user_settings.consent_passive_desc": "ปิดการค้นหาใบหน้า ระบบจะไม่ตรวจจับใบหน้าของคุณในภาพกิจกรรม และไม่ส่งการแจ้งเตือนใด ๆ",
    "user_settings.pref_card_title": "ปรับแต่งการยินยอมข้อมูลส่วนบุคคล (Update Preferences)",
    "user_settings.pref_card_desc": "กำหนดค่าความเป็นส่วนตัวตามพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล (PDPA)",
    "user_settings.withdraw_warning_title": "คำเตือน: คุณกำลังจะเพิกถอนความยินยอม",
    "user_settings.withdraw_warning_1": "ระบบ AI จะหยุดการตรวจจับและจับคู่ใบหน้าของคุณในภาพกิจกรรมใหม่ทันที",
    "user_settings.withdraw_warning_2": "ภาพของคุณจะไม่ปรากฏในการค้นหาอัตโนมัติ",
    "user_settings.withdraw_warning_3": "หากต้องการเปิดใช้งานใหม่ ท่านสามารถให้ความยินยอมและอัปโหลดรูปเซลฟี่อ้างอิงได้อีกครั้ง",
    "user_settings.rights_title": "สิทธิความเป็นส่วนตัวของคุณ (Your Privacy Rights)",
    "user_settings.rights_1": "คุณสามารถเพิกถอนความยินยอมหรือยกเลิกการค้นหาใบหน้าได้ตลอดเวลา",
    "user_settings.rights_2": "สามารถส่งคำร้องขอลบหรือเบลอภาพที่มีใบหน้าของคุณได้",
    "user_settings.rights_3": "สามารถดาวน์โหลดสำเนาข้อมูลหรือสั่งลบข้อมูลส่วนบุคคลทั้งหมดได้ทันที",
    "user_settings.btn_save": "บันทึกการตั้งค่าความเป็นส่วนตัว",
    "user_settings.btn_saving": "กำลังบันทึกข้อมูล...",
    "user_settings.ci_title": "การจัดการข้อมูลส่วนบุคคลแบบเบ็ดเสร็จ (Consent Intelligence Actions)",
    "user_settings.ci_export": "ดาวน์โหลดข้อมูลส่วนบุคคล (Export Data)",
    "user_settings.ci_delete": "ลบข้อมูลส่วนบุคคลทั้งหมด (Full Delete)",
    "user_settings.saved_success": "บันทึกการตั้งค่าความเป็นส่วนตัวเรียบร้อยแล้ว!",

    // Photographer Portal
    "portal.photographer_title": "PHOTOGRAPHER PORTAL",
    "portal.photographer_subtitle": "ระบบบริการช่างภาพกิจกรรม",
    "nav.workspace": "พื้นที่ทำงาน (Workspace)",
    "nav.photographer_profile": "โปรไฟล์ช่างภาพ (Profile)",
    "photo.workspace_badge": "ระบบบริการช่างภาพกิจกรรม",
    "photo.title": "Photographer Workspace",
    "photo.subtitle": "ระบบอัปโหลด จัดการ และติดตามสถิติภาพถ่ายกิจกรรมสำหรับช่างภาพ",
    "photo.loading.title": "กำลังโหลดข้อมูลพื้นที่ทำงานช่างภาพ...",
    "photo.loading.subtitle": "กำลังจัดเตรียมข้อมูลกิจกรรม คลังภาพถ่าย และสถิติการใช้งาน",
    "photo.auth.title": "จำเป็นต้องมีสิทธิ์ช่างภาพ (Access Required)",
    "photo.auth.desc": "กรุณาเข้าสู่ระบบด้วยบัญชีช่างภาพเพื่อเข้าใช้งานระบบอัปโหลดและจัดการภาพถ่าย",
    "photo.auth.signin": "เข้าสู่ระบบ (Sign In)",
    "photo.metric.ready": "พร้อมรับภาพถ่าย",
    "photo.metric.no_events": "ยังไม่มีกิจกรรม",
    "photo.metric.processing": "กำลังประมวลผล",
    "photo.metric.no_files_queue": "ยังไม่มีไฟล์ในคิว",
    "photo.step1_badge": "ขั้นตอนที่ 1",
    "photo.step2_badge": "ขั้นตอนที่ 2",
    "photo.tab.upload": "อัปโหลดภาพกิจกรรม (Upload)",
    "photo.tab.manage": "จัดการภาพถ่าย (Manage Uploads)",
    "photo.tab.analytics": "สถิติและการเข้าชม (Analytics)",
    "photo.upload.step1_title": "1. เลือกกิจกรรมเป้าหมาย (Select Event)",
    "photo.upload.step1_desc": "เลือกกิจกรรมที่ต้องการนำส่งภาพถ่ายเข้าสู่ระบบ",
    "photo.upload.select_placeholder": "-- เลือกกิจกรรม --",
    "photo.upload.event_selected_prefix": "ภาพจะถูกจัดเก็บเข้าสู่กิจกรรม:",
    "photo.upload.event_select_prompt": "กรุณาเลือกกิจกรรมก่อนดำเนินการอัปโหลดไฟล์",
    "photo.upload.no_event_selected": "ยังไม่ได้เลือกกิจกรรม",
    "photo.upload.event_label": "กิจกรรม:",
    "photo.upload.step2_title": "2. เลือกไฟล์ภาพถ่าย (Select Files)",
    "photo.upload.step2_desc": "ลากไฟล์มาวาง หรือเลือกไฟล์/โฟลเดอร์จากเครื่อง",
    "photo.upload.dropzone_text": "ลากและวางไฟล์ภาพถ่ายที่นี่",
    "photo.upload.dropzone_subtext": "รองรับไฟล์ JPG, PNG, WEBP และ HEIC (แปลงอัตโนมัติ)",
    "photo.upload.btn_select_files": "เลือกไฟล์ภาพ",
    "photo.upload.btn_select_folder": "เลือกทั้งโฟลเดอร์",
    "photo.upload.selected_summary": "ไฟล์ที่เลือกทั้งหมด",
    "photo.upload.clear_all": "ล้างรายการ",
    "photo.upload.btn_upload": "เริ่มอัปโหลดภาพถ่าย",
    "photo.upload.uploading": "กำลังอัปโหลดและประมวลผล...",
    "photo.upload.step3_title": "สถานะการอัปโหลด (Upload Status)",
    "photo.upload.files_in_queue": "ไฟล์ในคิวการอัปโหลด",
    "photo.upload.no_files": "ยังไม่มีไฟล์ที่เลือก",
    "photo.upload.queue_empty_guide": "เลือกไฟล์หรือโฟลเดอร์จากกล่องด้านซ้ายเพื่อเพิ่มรายการ",
    "photo.upload.btn_notify": "ส่งแจ้งเตือนการค้นหาใบหน้า (Notify Matches)",
    "photo.upload.notifying": "กำลังส่งแจ้งเตือน...",
    "photo.upload.notify_desc": "เมื่ออัปโหลดภาพกิจกรรมครบถ้วนแล้ว สามารถส่งระบบแจ้งเตือนสรุปผลการจับคู่ใบหน้าไปยังนักศึกษาและผู้เข้าร่วมงานที่มีรูปปรากฏได้ทันที",
    "photo.manage.title": "ภาพถ่ายที่อัปโหลดทั้งหมด",
    "photo.manage.desc": "ตรวจสอบสถานะการประมวลผล AI ลบภาพ หรือส่งประมวลผลซ้ำ",
    "photo.manage.search_placeholder": "ค้นหาชื่อกิจกรรม หรือชื่อไฟล์...",
    "photo.manage.total_photos": "ภาพในระบบ",
    "photo.manage.col_preview": "ตัวอย่าง",
    "photo.manage.col_file": "ชื่อไฟล์ / กิจกรรม",
    "photo.manage.col_date": "วันที่อัปโหลด",
    "photo.manage.col_status": "สถานะ AI",
    "photo.manage.col_actions": "การจัดการ",
    "photo.manage.empty": "ไม่พบประวัติการอัปโหลดภาพถ่าย",
    "photo.manage.empty_guide": "สลับไปยังแท็บอัปโหลดเพื่อเพิ่มภาพถ่ายเข้าสู่ระบบ",
    "photo.manage.retry": "ลองใหม่",
    "photo.manage.delete": "ลบภาพ",
    "photo.status.completed": "เสร็จสิ้น",
    "photo.status.processing": "กำลังประมวลผล",
    "photo.status.failed": "ล้มเหลว",
    "photo.status.pending": "รอดำเนินการ",
    "photo.analytics.loading": "กำลังประมวลผลข้อมูลสถิติ...",
    "photo.analytics.empty_events": "ยังไม่มีข้อมูลสถิติรายกิจกรรม",
    "photo.analytics.metric.events": "กิจกรรมที่เข้าร่วม",
    "photo.analytics.metric.photos": "ภาพถ่ายทั้งหมด",
    "photo.analytics.metric.views": "ยอดการเข้าชมรวม",
    "photo.analytics.metric.downloads": "ยอดดาวน์โหลดรวม",
    "photo.analytics.chart_title": "แนวโน้มยอดการเข้าชมและดาวน์โหลด (Engagement Trends)",
    "photo.analytics.chart_desc": "สถิติการเข้าดูและดาวน์โหลดภาพถ่ายกิจกรรมย้อนหลัง",
    "photo.analytics.7days": "7 วันย้อนหลัง",
    "photo.analytics.14days": "14 วันย้อนหลัง",
    "photo.analytics.views_label": "ยอดเข้าชม (Views)",
    "photo.analytics.downloads_label": "ยอดดาวน์โหลด (Downloads)",
    "photo.analytics.event_stats_title": "สถิติรายกิจกรรม (Per-Event Breakdown)",
    "photo.analytics.col_event": "ชื่อกิจกรรม",
    "photo.analytics.col_photos": "จำนวนภาพ",
    "photo.analytics.col_views": "การเข้าชม",
    "photo.analytics.col_downloads": "ดาวน์โหลด",
    "photo.profile.title": "การตั้งค่า (Settings)",
    "photo.profile.subtitle": "ข้อมูลบัญชีและสถิติการทำงานช่างภาพประจำสถาบัน",
    "photo.profile.back": "กลับหน้าพื้นที่ทำงาน",
    "photo.profile.role_badge": "ช่างภาพประจำระบบ (Authorized Photographer)",
    "photo.profile.email_label": "อีเมลติดต่อ (Contact Email)",
    "photo.profile.account_status": "สถานะบัญชี (Account Status)",
    "photo.profile.active": "เปิดใช้งานปกติ (Active)",
    "photo.profile.stat_total": "ภาพที่อัปโหลดสะสม",
    "photo.profile.stat_completed": "ประมวลผลสำเร็จ",
    "photo.profile.stat_processing": "กำลังประมวลผล",
    "photo.profile.stat_events": "กิจกรรมที่รับผิดชอบ",
    "photo.profile.metrics_title": "สถิติการทำงานในระบบ (Activity Metrics)",
    "photo.profile.guidelines_title": "ข้อกำหนดและแนวทางการปฏิบัติงานสำหรับช่างภาพ (Photographer Guidelines)",
    "photo.profile.guide1_title": "การระบุกิจกรรมที่ถูกต้อง",
    "photo.profile.guide1_desc": "เลือกกิจกรรมเป้าหมายให้ถูกต้องก่อนอัปโหลด เพื่อให้ระบบ AI ทำการวิเคราะห์และดัชนีใบหน้าตรงตามงาน",
    "photo.profile.guide2_title": "คุณภาพของไฟล์ภาพ",
    "photo.profile.guide2_desc": "รองรับไฟล์ JPG, PNG และ HEIC (แปลงให้อัตโนมัติ) ขนาดไฟล์สูงสุดไม่เกิน 15MB ต่อภาพ",
    "photo.profile.guide3_title": "การแจ้งเตือนผู้มีสิทธิ์",
    "photo.profile.guide3_desc": "หลังการอัปโหลดครบทุกรูป สามารถกดปุ่ม Notify เพื่อส่งสรุปผลการจับคู่ภาพไปยังนักศึกษา",
    "photo.profile.guide4_title": "การปฏิบัติตามมาตรฐาน PDPA",
    "photo.profile.guide4_desc": "ระบบจะบันทึกประวัติการอัปโหลดและจัดการข้อมูลภาพถ่ายอย่างเคร่งครัดตามนโยบายความเป็นส่วนตัว",

    // Privacy Policy Page
    "privacy.badge": "ความโปร่งใสและมาตรฐาน PDPA",
    "privacy.title": "นโยบายความเป็นส่วนตัวและการจัดการข้อมูล",
    "privacy.subtitle": "ระบบ PhotoFinder มุ่งมั่นปกป้องข้อมูลส่วนบุคคลของนักศึกษาและบุคลากร โดยใช้ปัญญาประดิษฐ์ (AI) เพื่ออำนวยความสะดวกในการค้นหาภาพกิจกรรมมหาวิทยาลัยเท่านั้น ไม่มีการนำข้อมูลไปใช้ในเชิงพาณิชย์ และคุณสามารถควบคุมข้อมูลของตนเองได้อย่างสมบูรณ์",
    "privacy.last_updated": "ปรับปรุงล่าสุดเมื่อ",
    "privacy.nav.back": "กลับสู่ระบบ",
    "privacy.nav.settings": "ตั้งค่าความเป็นส่วนตัว",
    "privacy.pill.pdpa": "มาตรฐาน PDPA 2562",
    "privacy.pill.retention": "ลบข้อมูลอัตโนมัติ 30 วัน",
    "privacy.pill.vector": "เวกเตอร์คณิตศาสตร์ 512 มิติ",
    "privacy.pill.control": "ผู้ใช้ควบคุมได้ 100%",
    "privacy.jump.lifecycle": "วงจรข้อมูล AI",
    "privacy.jump.guarantees": "สิ่งที่เราสัญญา",
    "privacy.jump.retention": "การลบภาพ 30 วัน",
    "privacy.jump.rights": "สิทธิ์ตาม PDPA",
    "privacy.jump.security": "มาตรฐานความปลอดภัย",
    "privacy.jump.faq": "คำถามที่พบบ่อย",
    "privacy.lifecycle.title": "1. วงจรการประมวลผลข้อมูล AI (AI Data Lifecycle)",
    "privacy.lifecycle.desc": "ทำความเข้าใจว่าระบบแปลงภาพถ่ายเป็นข้อมูลทางคณิตศาสตร์อย่างไร โดยไม่มีการจัดเก็บข้อมูลชีวมาตรถาวร",
    "privacy.step1.title": "1. นำเข้าภาพถ่าย",
    "privacy.step1.desc": "ช่างภาพอัปโหลดภาพกิจกรรม หรือผู้ใช้อัปโหลดรูปเซลฟี่อ้างอิงเพื่อใช้เปรียบเทียบหาภาพตนเอง",
    "privacy.step2.title": "2. ถอดรหัสเวกเตอร์ 512 มิติ",
    "privacy.step2.desc": "AI สกัดจุดเด่นบนใบหน้าเป็นชุดตัวเลข 512 มิติ (Face Embedding) เข้ารหัส ไม่ใช่ไฟล์รูปภาพดั้งเดิม",
    "privacy.step3.title": "3. จับคู่ด้วย Cosine Similarity",
    "privacy.step3.desc": "คำนวณระยะห่างทางคณิตศาสตร์ในหน่วยความจำเพื่อค้นหาภาพที่มีใบหน้าตรงกันอย่างแม่นยำ",
    "privacy.step4.title": "4. ลบถาวรอัตโนมัติ 30 วัน",
    "privacy.step4.desc": "ภาพกิจกรรม เวกเตอร์ใบหน้า และข้อมูลแคชทั้งหมดจะถูกลบทิ้งอย่างถาวรเมื่อครบกำหนด 30 วัน",
    "privacy.do_dont.title": "2. คำมั่นสัญญาในการปกป้องข้อมูล (Guarantees & Prohibitions)",
    "privacy.do_dont.desc": "ความโปร่งใสสูงสุด สิ่งที่ระบบดำเนินการเพื่อความปลอดภัย และสิ่งที่เราไม่มีวันทำเด็ดขาด",
    "privacy.dos.title": "สิ่งที่เราทำเพื่อคุณ (What We Do)",
    "privacy.dos.item1": "ใช้ข้อมูลเวกเตอร์ใบหน้าเพื่อค้นหาภาพกิจกรรมตามที่คุณยินยอมเท่านั้น",
    "privacy.dos.item2": "เก็บรูปเซลฟี่อ้างอิงในพื้นที่ส่วนบุคคลที่มีการเข้ารหัส และลบได้ตลอดเวลาในคลิกเดียว",
    "privacy.dos.item3": "ลบภาพถ่ายกิจกรรมและเวกเตอร์ทั้งหมดออกจากเซิร์ฟเวอร์และคลาวด์อัตโนมัติภายใน 30 วัน",
    "privacy.dos.item4": "เปิดให้ขอลบภาพหรือเบลอใบหน้าออกจากกิจกรรมได้ทันทีผ่านปุ่มบนรูปภาพ",
    "privacy.dos.item5": "ให้สิทธิ์ในการส่งออกข้อมูลทั้งหมด (Export) หรือล้างบัญชีถาวร (Right to be Forgotten)",
    "privacy.donts.title": "สิ่งที่เราไม่มีวันทำเด็ดขาด (What We NEVER Do)",
    "privacy.donts.item1": "ไม่ขาย ส่งต่อ หรือแสวงหากำไรจากข้อมูลส่วนบุคคลและภาพถ่ายแก่บุคคลภายนอกเด็ดขาด",
    "privacy.donts.item2": "ไม่ใช้ระบบเพื่อตรวจเช็กชื่อ การเข้าชั้นเรียน หรือการสอดส่องพฤติกรรมใดๆ ทั้งสิ้น",
    "privacy.donts.item3": "ไม่นำภาพถ่ายหรือข้อมูลใบหน้าไปเทรนโมเดล AI ภายนอกในเชิงพาณิชย์",
    "privacy.donts.item4": "ไม่เก็บรักษาภาพถ่ายกิจกรรมไว้อย่างถาวรหลังพ้นกำหนดระยะเวลา 30 วัน",
    "privacy.donts.item5": "ไม่อนุญาตให้บุคคลภายนอกที่ไม่ได้ยืนยันตัวตนเข้าถึงฐานข้อมูลภาพถ่าย",
    "privacy.retention.title": "3. ระยะเวลาการจัดเก็บและการลบอัตโนมัติ (Retention & Lifecycle)",
    "privacy.retention.desc": "หลักการจำกัดระยะเวลาจัดเก็บข้อมูลตามมาตรฐาน PDPA สากล",
    "privacy.retention.events_title": "ภาพถ่ายกิจกรรมมหาวิทยาลัย (Event Photos - ชั่วคราว 30 วัน)",
    "privacy.retention.events_desc": "ภาพถ่ายกิจกรรมทั้งหมดมีอายุการจัดเก็บสูงสุดไม่เกิน 30 วันนับจากวันที่เผยแพร่กิจกรรม เมื่อครบกำหนด ระบบ Cron Worker จะทำการลบไฟล์ภาพออกจาก Cloudinary CDN และลบข้อมูล Facial Embedding ทั้งหมดออกจากฐานข้อมูลอย่างถาวรโดยไม่สามารถกู้คืนได้",
    "privacy.retention.selfie_title": "รูปภาพเซลฟี่อ้างอิง (Reference Selfie - อยู่ภายใต้การควบคุมของคุณ)",
    "privacy.retention.selfie_desc": "รูปเซลฟี่ที่คุณอัปโหลดไว้เพื่อค้นหาใบหน้าตนเอง จะถูกจัดเก็บไว้อย่างปลอดภัยในบัญชีของคุณเพื่อความสะดวกในการค้นหากิจกรรมใหม่ๆ โดยคุณสามารถกด 'รีเซ็ตโปรไฟล์' หรือเพิกถอนความยินยอมเพื่อลบภาพและเวกเตอร์ได้ทันทีในหน้า Settings",
    "privacy.retention.logs_title": "บันทึกการใช้งานระบบ (Audit & Security Logs - 90 วัน)",
    "privacy.retention.logs_desc": "เก็บบันทึกการเข้าใช้งานระบบเพื่อความปลอดภัยและการตรวจสอบตาม พ.ร.บ. คอมพิวเตอร์ โดยมีการตัดทอนข้อมูลส่วนบุคคลและล้างประวัติทุก 90 วัน",
    "privacy.rights.title": "4. สิทธิของเจ้าของข้อมูลส่วนบุคคล (Your Rights Under PDPA)",
    "privacy.rights.desc": "คุณมีสิทธิตามพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 ดังต่อไปนี้",
    "privacy.rights.withdraw_title": "สิทธิเพิกถอนความยินยอม (Right to Withdraw Consent)",
    "privacy.rights.withdraw_desc": "สามารถปิดระบบค้นหาใบหน้า (Opt-out) ได้ตลอดเวลาในหน้าตั้งค่า เมื่อปิดแล้ว ระบบจะไม่ทำการสแกนหาใบหน้าของคุณในกิจกรรมใหม่อีกต่อไป",
    "privacy.rights.erasure_title": "สิทธิขอให้ลบหรือทำลาย (Right to Erasure / Right to be Forgotten)",
    "privacy.rights.erasure_desc": "หากพบภาพถ่ายที่ไม่ประสงค์จะให้อยู่ในระบบ สามารถกดปุ่ม 'ขอให้ลบภาพ' หรือ 'ขอให้เบลอภาพ' ที่รูปภาพนั้นๆ ได้ทันที ผู้ดูแลระบบจะดำเนินการตรวจสอบและลบออกจากระบบทันที",
    "privacy.rights.portability_title": "สิทธิขอรับข้อมูล (Right to Data Portability)",
    "privacy.rights.portability_desc": "สามารถกด 'One-Click Export Data' ในหน้าตั้งค่า เพื่อดาวน์โหลดประวัติข้อมูลส่วนบุคคลและภาพถ่ายทั้งหมดของคุณในรูปแบบไฟล์ JSON",
    "privacy.rights.wipe_title": "สิทธิล้างข้อมูลทั้งหมด (One-Click Full Delete)",
    "privacy.rights.wipe_desc": "สามารถขอลบประวัติ ข้อมูลโปรไฟล์ รูปเซลฟี่ และเวกเตอร์ทั้งหมดออกจากระบบได้อย่างสมบูรณ์ในคลิกเดียว",
    "privacy.rights.btn_settings": "ไปยังหน้าจัดการความเป็นส่วนตัว (Settings)",
    "privacy.security.title": "5. สถาปัตยกรรมความปลอดภัย (Security & Architecture)",
    "privacy.security.desc": "โครงสร้างทางเทคนิคที่ใช้ในการรักษาความลับและความปลอดภัยของข้อมูลในระบบ",
    "privacy.security.item1_title": "การเข้ารหัสระดับมาตรฐานสากล (End-to-End Encryption)",
    "privacy.security.item1_desc": "รับส่งข้อมูลผ่าน HTTPS / TLS 1.3 และเข้ารหัสข้อมูลสำคัญในฐานข้อมูลด้วยมาตรฐาน AES-256",
    "privacy.security.item2_title": "การจำกัดสิทธิ์ระดับแถวข้อมูล (Row-Level Isolation)",
    "privacy.security.item2_desc": "ระบบฐานข้อมูล PostgreSQL แยกสิทธิ์การเข้าถึงข้อมูลตามบทบาท (RBAC) นักศึกษาไม่สามารถเข้าถึงข้อมูลของผู้ใช้อื่นได้",
    "privacy.security.item3_title": "ลิงก์เข้าถึงภาพแบบจำกัดเวลา (Signed CDN URLs)",
    "privacy.security.item3_desc": "ภาพถ่ายบน Cloudinary เข้าถึงผ่าน URL ที่ลงนามดิจิทัลพร้อมกำหนดเวลาหมดอายุ ป้องกันการคัดลอกลิงก์ออกไปภายนอก",
    "privacy.security.item4_title": "ระบบประมวลผล AI แยกเฉพาะส่วน (Sandboxed AI)",
    "privacy.security.item4_desc": "บริการ AI Service ทำงานในคอนเทนเนอร์แยกเฉพาะ ไม่มีการส่งข้อมูลภาพออกไปยัง AI ภายนอกหรือบริการคลาวด์สาธารณะ",
    "privacy.faq.title": "6. คำถามที่พบบ่อย (Frequently Asked Questions)",
    "privacy.faq.desc": "ข้อสงสัยทั่วไปเกี่ยวกับความเป็นส่วนตัวและการใช้งานระบบ PhotoFinder",
    "privacy.faq.q1": "จำเป็นต้องอัปโหลดรูปเซลฟี่เพื่อใช้งานระบบหรือไม่?",
    "privacy.faq.a1": "ไม่จำเป็น คุณสามารถเข้าดูภาพกิจกรรมทั้งหมดในมหาวิทยาลัยและดาวน์โหลดภาพได้ตามปกติโดยไม่ต้องอัปโหลดรูปเซลฟี่ การอัปโหลดรูปเซลฟี่มีไว้เฉพาะสำหรับผู้ที่ต้องการให้ระบบ AI ช่วยค้นหาภาพตนเองอัตโนมัติเท่านั้น",
    "privacy.faq.q2": "ระบบจะลบรูปภาพกิจกรรมจริงหรือไม่ หลังครบ 30 วัน?",
    "privacy.faq.a2": "จริงอย่างแน่นอน ระบบมีกระบวนการตรวจสอบอัตโนมัติ (Cron Job) ที่ทำงานทุกวัน เพื่อลบภาพกิจกรรมที่เกินกำหนด 30 วันออกจากทั้งคลังภาพ Cloudinary และฐานข้อมูล PostgreSQL รวมถึงข้อมูลเวกเตอร์ใบหน้าทั้งหมดโดยไม่สามารถกู้คืนได้",
    "privacy.faq.q3": "เพื่อนหรือบุคคลภายนอกสามารถใช้รูปของฉันเพื่อค้นหาภาพได้หรือไม่?",
    "privacy.faq.a3": "ไม่ได้ ระบบจำกัดสิทธิ์ให้ค้นหาได้เฉพาะในบัญชีของผู้ใช้ที่เข้าสู่ระบบผ่าน Google MFU ของตนเองเท่านั้น และมีระบบ Identity Guard เพื่อป้องกันการนำภาพบุคคลอื่นมาอัปโหลดเป็นเซลฟี่อ้างอิง",
    "privacy.faq.q4": "หากพบภาพที่ไม่ต้องการให้เผยแพร่ ต้องทำอย่างไร?",
    "privacy.faq.a4": "คุณสามารถคลิกที่ภาพนั้นแล้วกดปุ่ม 'ขอให้ลบภาพ' (Request Removal) หรือ 'ขอให้เบลอภาพ' (Request Blur) ได้ทันที คำร้องจะถูกส่งตรงไปยังเจ้าหน้าที่ดูแลระบบเพื่อพิจารณาดำเนินการทันที",
    "privacy.faq.q5": "ข้อมูลเวกเตอร์ 512 มิติ สามารถนำไปสร้างภาพใบหน้าเดิมขึ้นมาใหม่ได้หรือไม่?",
    "privacy.faq.a5": "ไม่ได้ ข้อมูล Embedding เป็นเพียงค่าพิกัดทางคณิตศาสตร์แบบ One-way ที่ใช้เปรียบเทียบระยะห่างเท่านั้น ไม่สามารถนำค่าตัวเลขดังกล่าวมาย้อนกลับเป็นภาพใบหน้าต้นฉบับได้",
    "privacy.contact.title": "ติดต่อเจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล (DPO Contact)",
    "privacy.contact.desc": "หากมีข้อสงสัย ข้อเสนอแนะ หรือต้องการใช้สิทธิตามกฎหมาย PDPA กรุณาติดต่อทีมงานและเจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล",
    "privacy.contact.univ": "มหาวิทยาลัยแม่ฟ้าหลวง (Mae Fah Luang University)",
    "privacy.contact.addr": "333 หมู่ 1 ต.ท่าสุด อ.เมือง จ.เชียงราย 57100",
    "privacy.contact.email_label": "อีเมลติดต่อ (Email):",
    "privacy.contact.email_val": "dpo@mfu.ac.th, photofinder-support@mfu.ac.th",
    "privacy.contact.hours_label": "เวลาทำการ (Office Hours):",
    "privacy.contact.hours_val": "วันจันทร์ - ศุกร์ 08:00 - 16:00 น. (เว้นวันหยุดราชการ)",

    // Photo Detail Modal
    "detail.photo_moment": "ภาพกิจกรรม",
    "detail.match": "ความแม่นยำ",
    "detail.saved": "บันทึกแล้ว",
    "detail.favorite": "บันทึกรูป",
    "detail.share": "แชร์",
    "detail.download_original": "ดาวน์โหลดภาพต้นฉบับ",
    "detail.share_to": "แชร์ไปยัง",
    "detail.request_removal": "แจ้งขอลบภาพ",
    "detail.removal_title": "คำร้องขอลบภาพถ่าย",
    "detail.removal_desc": "ทีมงานจะตรวจสอบคำร้องของคุณภายใน 24 ชั่วโมง โดยคุณจะได้รับการยืนยันทางอีเมล",
    "detail.group_photos_label": "ภาพหมู่:",
    "detail.group_photos_desc": "หากภาพนี้มีบุคคลอื่นอยู่ด้วย ทีมงานอาจดำเนินการเบลอหรือใส่โมเสกเฉพาะใบหน้าของคุณแทนการลบภาพทั้งหมด เพื่อคุ้มครองความเป็นส่วนตัวของคุณและรักษากิจกรรมของผู้อื่น",
    "detail.reason_label": "เหตุผลในการขอลบ",
    "detail.reason_placeholder": "กรุณาระบุเหตุผลที่ต้องการให้ลบภาพนี้",
    "detail.submitting": "กำลังส่งคำร้อง...",
    "detail.submit_request": "ส่งคำร้อง",
    "detail.cancel": "ยกเลิก",
    "detail.zoom_in": "ซูมเข้า",
    "detail.zoom_out": "ซูมออก",
    "detail.enter_fullscreen": "ดูเต็มจอ",
    "detail.exit_fullscreen": "ออกจากเต็มจอ",
    "detail.close": "ปิด",
    "detail.share_error": "ไม่สามารถเปิดการแชร์ได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง",
    "detail.favorite_remove_error": "ไม่สามารถลบภาพนี้ออกจากรายการบันทึกได้ในขณะนี้",
    "detail.favorite_add_error": "ไม่สามารถบันทึกภาพนี้ได้ในขณะนี้",
    "detail.favorite_update_error": "ไม่สามารถอัปเดตสถานะการบันทึกได้ในขณะนี้",
    "detail.fullscreen_error": "เบราว์เซอร์นี้ไม่รองรับการแสดงผลแบบเต็มหน้าจอ",
    "detail.reason_required": "กรุณาระบุเหตุผลในการขอลบภาพ",
    "detail.removal_failed": "ไม่สามารถส่งคำร้องขอลบภาพได้ กรุณาลองใหม่อีกครั้ง",
    "detail.removal_success": "ส่งคำร้องขอลบภาพเรียบร้อยแล้ว ทีมงานจะตรวจสอบภายใน 24 ชั่วโมง",
    "detail.error_generic": "เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง",
  },
  en: {
    // Header & Global
    "portal.title": "ADMIN PORTAL",
    "portal.subtitle": "Central Management System",
    "portal.system_online": "System Status: Online",
    "nav.home": "Home",
    "nav.admin": "Administrator Portal",
    "nav.dashboard": "Overview Dashboard",
    "nav.settings": "Settings",
    "nav.profile": "Settings",
    "nav.privacy": "Privacy Policy",
    "nav.signout": "Sign Out",
    "role.admin": "Administrator (Admin)",
    "role.photographer": "Photographer",
    "role.student": "Student",
    "role.super_admin": "Super Administrator",

    // Breadcrumbs
    "breadcrumb.home": "Home",
    "breadcrumb.admin": "Administrator (Admin)",
    "breadcrumb.dashboard": "Overview Dashboard",
    "breadcrumb.create_event": "Create New Event",
    "breadcrumb.edit_event": "Edit Event",
    "breadcrumb.profile": "Settings",
    "breadcrumb.settings": "Settings",
    "breadcrumb.back": "Back to Dashboard",

    // Navigation Extras
    "nav.my_photos": "My Photos",
    "nav.favorites": "Favorites",
    "student.space": "Student space",
    "student.welcome": "Welcome back,",
    "student.description": "Your personal event photo space. Set your profile once and let Photo Finder bring your moments to you.",
    "student.profile_signal": "Profile signal",
    "student.active": "Active",
    "student.inactive": "Inactive",
    "student.ready": "Ready to match",
    "student.not_set_up": "Not set up",
    "student.ready_description": "New event photos will be checked automatically.",
    "student.not_set_up_description": "Add a selfie to start finding your event photos.",
    "student.auto_matches": "Auto matches",
    "student.saved_moments": "Saved moments",
    "student.profile_status": "Profile status",
    "student.update_profile": "Update profile",
    "student.set_selfie": "Set up my selfie",
    "student.remove_profile": "Remove profile photo",
    "student.remove_profile_confirm": "Are you sure you want to remove your profile selfie?",
    "student.remove_profile_modal_title": "Confirm Profile Selfie Removal",
    "student.remove_profile_modal_desc": "Are you sure you want to remove your reference selfie and facial vector data from the system?",
    "student.remove_profile_consequence": "Automatic photo matching across campus events will be paused until you register a new selfie.",
    "student.remove_profile_cancel": "Cancel",
    "student.remove_profile_action": "Remove photo",
    "student.remove_profile_deleting": "Removing...",
    "student.remove_profile_error": "Failed to delete reference photo.",
    "student.network_error": "Network error. Please try again.",
    "student.browse_photos": "Browse photos",
    "student.collection": "Your collection",
    "student.recently_matched": "Your Event Moments",
    "student.no_matches": "No matches yet",
    "student.no_matches_description": "Check back after your next campus event.",
    "student.view_all": "View all",
    "student.settings_title": "Settings",
    "student.settings_subtitle": "Manage account details, notification channels, and privacy consent (PDPA)",
    "student.account_section": "Account Information",
    "student.account_desc": "Account authenticated via Mae Fah Luang University Google Workspace",
    "student.ref_face_title": "Reference Face Status",
    "student.ref_face_registered": "Face Registered",
    "student.ref_face_unregistered": "No Face Registered",
    "student.ref_face_update": "Update Selfie",
    "student.ref_face_set": "Register Selfie",
    "student.notif_section": "Notification Channels",
    "student.notif_desc": "Receive real-time notifications when AI discovers your photos in campus events",
    "student.line_title": "LINE Official Account",
    "student.line_desc": "Get instant photo alerts and previews via LINE message",
    "student.line_connected": "Connected",
    "student.line_not_connected": "Not Connected",
    "student.line_link_btn": "Connect LINE",
    "student.line_unlink_btn": "Disconnect",
    "student.line_add_friend": "Please add our LINE OA first: @042nimvi",
    "student.email_title": "Email Notification",
    "student.email_desc": "Send email summaries when new event photos featuring you are uploaded",
    "student.email_active": "Enabled",
    "student.email_inactive": "Disabled",
    "student.privacy_section": "Privacy & PDPA Consent",
    "student.privacy_desc": "Control facial data processing preferences and exercise data subject rights under PDPA",
    "student.consent_face_title": "Enable AI Face Matching",
    "student.consent_face_desc": "Allow the AI to identify your face in event photos and organize them into your personal gallery",
    "student.consent_data_title": "Biometric Data Processing Consent",
    "student.consent_data_desc": "Consent to the secure storage and processing of facial vector embeddings in accordance with PDPA",
    "student.rights_section": "Data Subject Rights",
    "student.rights_desc": "Exercise your PDPA rights to export a copy of your records or permanently erase all personal data",
    "student.btn_export": "Export Personal Data",
    "student.btn_export_desc": "Download a complete copy of your profile and data records as JSON",
    "student.btn_delete": "Delete All Personal Data",
    "student.btn_delete_desc": "Permanently erase reference selfie, facial vectors, and saved moments",
    "student.btn_save": "Save Preferences",
    "student.btn_saving": "Saving...",
    "student.save_success": "Settings saved successfully",
    "student.save_error": "Failed to save preferences. Please try again.",
    "student.withdraw_warning": "When face search is disabled, the AI will not automatically match or notify you about new event photos",
    "student.withdraw_face_warning": "Automated face search is disabled: The AI will not automatically match or notify you about new event photos, but your reference face remains securely stored.",
    "student.withdraw_data_warning": "Warning: Disabling biometric data processing (PDPA) will remove your reference selfie and suspend all AI features.",
    "student.consent_modal_title": "Consent Required",
    "student.consent_modal_desc": "Enable these before using face search:",
    "student.consent_modal_face_title": "AI face search",
    "student.consent_modal_face_desc": "Find your face in event photos.",
    "student.consent_modal_data_title": "Data processing",
    "student.consent_modal_data_desc": "Your biometric data is processed securely.",
    "student.consent_modal_dismiss": "Dismiss",
    "student.consent_modal_settings": "Go to Settings",
    "student.updating_profile": "Updating your profile...",
    "student.mapping_face": "Mapping your face...",
    "student.profile_title": "Settings",
    "student.profile_subtitle": "Manage account details, notification preferences, and privacy consent (PDPA)",
    "student.profile_back": "Back to Home",
    "student.role_badge": "Student",
    "student.metrics_title": "Account Statistics",
    "student.stat_matches": "Matched Photos",
    "student.stat_saved": "Saved Photos",
    "student.stat_face": "Reference Face",
    "student.stat_notifications": "Notifications",
    "student.face_ready": "Ready",
    "student.face_none": "Not Set Up",
    "student.notifications_title": "Notification Channels",
    "student.notifications_desc": "Configure real-time notifications when your photos are discovered at campus events",
    "student.privacy_title": "Privacy & PDPA Consent",
    "nav.student_profile": "Settings",
    "favorites.space": "Your photo space",
    "favorites.title": "Favorites",
    "favorites.description": "All the event photos you saved, kept in one place.",
    "favorites.count": "saved photos",
    "favorites.collection": "Your collection",
    "favorites.saved_collection": "Saved photos",
    "favorites.loading": "Loading your saved photos...",
    "favorites.error": "Unable to load your favorites at this time. Please try again later.",
    "favorites.empty": "No saved photos yet",
    "favorites.empty_description": "Tap the heart icon on any photo you love to save it here.",
    "search.space": "Photo library",
    "search.title": "Browse photos",
    "search.description": "Find photos from campus events.",
    "search.count": "photos",
    "search.loading": "Loading photos...",
    "search.error": "Unable to load photos.",
    "search.empty": "No photos yet",

    // Dashboard Banner & Metrics
    "dash.title": "Admin Dashboard",
    "dash.welcome": "Central Management System | Welcome,",
    "dash.btn.create_event": "Create Event",
    "dash.btn.settings": "System Settings",
    "dash.metric.active_events": "Active Events",
    "dash.metric.total_events": "Total Events",
    "dash.metric.pending_requests": "Pending Requests",
    "dash.metric.total_users": "Registered Users",
    "dash.metric.out_of": "out of",
    "dash.metric.events_unit": "events",
    "dash.metric.in_db": "recorded in database",
    "dash.metric.awaiting_review": "awaiting moderation",
    "dash.metric.all_roles": "all roles combined",

    // Dashboard Menu
    "menu.title": "Main Menu",
    "menu.events": "Event Management",
    "menu.photos": "Photos Catalog",
    "menu.low_confidence": "AI Review Queue",
    "menu.requests": "Removal Requests",
    "menu.users": "User Management",
    "menu.health": "System Health",
    "menu.audit_logs": "Audit Logs (Super Admin)",

    // Audit Logs Tab
    "audit.title": "Security & PDPA Audit Logs",
    "audit.desc": "Track administrator activities, permission changes, and biometric data lifecycle",
    "audit.retention_notice": "PDPA Compliance Retention (90 Days): All security and administrative audit logs are retained for 90 days in accordance with data protection regulations. Expired logs are automatically purged nightly by the system cron.",
    "audit.search_placeholder": "Search by actor email, target, or action keyword...",
    "audit.export_csv": "Export CSV",
    "audit.category_all": "All Categories",
    "audit.category_biometrics": "Biometrics & Privacy",
    "audit.category_users": "User Management",
    "audit.category_content": "Content Moderation",
    "audit.category_security": "System Security",
    "audit.col_time": "Timestamp",
    "audit.col_actor": "Actor",
    "audit.col_action": "Action",
    "audit.col_target": "Target",
    "audit.col_details": "Details",
    "audit.empty": "No audit records found matching the current filters.",

    // Events Tab
    "events.title": "Events List",
    "events.desc": "Manage campus events, filter by keywords, and update publication status",
    "events.search_placeholder": "Search event by name...",
    "events.create_btn": "Create",
    "events.loading": "Loading campus events...",
    "events.not_found": "No events found",
    "events.not_found_desc": "Try a different search keyword or create a new event",
    "events.col.name": "Event Name",
    "events.col.date": "Event Date",
    "events.col.created": "Created At",
    "events.col.status": "Status",
    "events.col.actions": "Actions",
    "events.status.published": "Published",
    "events.status.draft": "Draft",
    "events.status.archived": "Archived",
    "events.btn.edit": "Edit",
    "events.btn.delete": "Delete",

    // Photos Tab
    "photos.title": "All Uploaded Photos",
    "photos.desc": "All event photos uploaded and indexed in the system",
    "photos.search_placeholder": "Search by event or filename...",
    "photos.loading": "Loading photos...",
    "photos.not_found": "No photos found",
    "photos.not_found_desc": "Uploaded photos will be displayed here for moderation",
    "photos.items_count": "photos",

    // Low Confidence Queue Tab
    "lc.title": "Low-Confidence AI Queue",
    "lc.desc": "Review photos where facial detection confidence falls below threshold",
    "lc.search_placeholder": "Search event...",
    "lc.threshold": "Threshold:",
    "lc.refresh": "Refresh",
    "lc.refreshing": "Refreshing...",
    "lc.loading": "Loading review queue...",
    "lc.clear": "Queue is clear",
    "lc.clear_desc": "All photos meet the required facial confidence criteria",
    "lc.min_confidence": "Min Confidence:",
    "lc.lc_faces": "Low-confidence faces:",
    "lc.total_faces": "Total faces:",
    "lc.btn.review": "Review Photo",
    "lc.modal.title": "Low-Confidence Photo Review",
    "lc.modal.preview_btn": "Preview Full Size",
    "lc.modal.approve_btn": "Approve Photo",
    "lc.modal.approving": "Approving...",
    "lc.modal.delete_btn": "Delete Photo",
    "lc.modal.goto_event": "Go to Event Edit",

    // Removal Requests Tab
    "req.title": "Photo Removal & Blur Requests",
    "req.desc": "Review and action privacy removal requests submitted by campus users",
    "req.loading": "Loading removal requests...",
    "req.clear": "No pending removal requests",
    "req.clear_desc": "When users request photo removal or blur, items appear here",
    "req.requested_by": "Requested by",
    "req.on_date": "on",
    "req.at_time": "at",
    "req.reason_label": "Reason Provided:",
    "req.btn.approve_delete": "Approve & Delete",
    "req.btn.approve_blur": "Approve & Blur",
    "req.btn.reject": "Reject Request",
    "req.processing": "Processing...",

    // User Management Tab
    "users.title": "All Registered Users",
    "users.desc": "Complete directory of users and account permissions",
    "users.add_photographer.title": "Add Photographer",
    "users.add_photographer.desc": "Enter a Google or MFU email. The user will be routed to photographer upload portal on login.",
    "users.add_photographer.placeholder": "photographer@gmail.com or photographer@mfu.ac.th",
    "users.add_photographer.btn": "Assign Photographer",
    "users.add_admin.title": "Add Administrator",
    "users.add_admin.desc": "Only Super Administrators can assign or remove administrator privileges.",
    "users.add_admin.placeholder": "admin@gmail.com",
    "users.add_admin.btn": "Assign Admin",
    "users.search_placeholder": "Search by name or email...",
    "users.col.details": "User Details",
    "users.col.status": "Status",
    "users.col.role": "Role",
    "users.col.actions": "Actions",
    "users.status.active": "Active",
    "users.status.blocked": "Blocked",
    "users.btn.block": "Block",
    "users.btn.unblock": "Unblock",
    "users.btn.demote": "Demote",
    "users.btn.delete": "Delete",
    "users.not_found": "No users found",
    "users.not_found_desc": "Try adjusting your search criteria",

    // System Health & Danger Zone
    "health.title": "System Health & Performance",
    "health.desc": "Real-time metrics and performance monitoring",
    "health.total_users": "Total Users",
    "health.total_events": "Total Events",
    "health.total_photos": "Total Photos",
    "health.faces_detected": "Faces Detected",
    "health.active_events": "Active Events",
    "health.ai_confidence": "AI Model Confidence",
    "health.ai_confidence_desc": "Average certainty across all predictions",
    "health.events_by_status": "Events by Status",
    "health.events_status_desc": "Distribution of event statuses",
    "health.photos_by_status": "Photos by Status",
    "health.photos_status_desc": "Photo processing breakdown",
    "health.users_by_role": "Users by Role",
    "health.users_role_desc": "User role distribution",
    "health.danger.title": "Danger Zone",
    "health.danger.desc": "Irreversible administrative actions affecting large volumes of data",
    "health.danger.wipe_title": "Wipe All Old Identity Selfies",
    "health.danger.wipe_desc": "Force all students to re-verify their face identity using Identity Guard",
    "health.danger.wipe_btn": "Wipe & Reset Selfies",

    // Event Create & Edit
    "event_form.create_title": "Create New Event",
    "event_form.create_subtitle": "Configure a new campus event for photo uploads and AI student face search",
    "event_form.edit_title": "Edit Event Details",
    "event_form.edit_subtitle": "Update event title, occurrence date, and public access status",
    "event_form.card_title": "Event Information",
    "event_form.card_desc": "Fill in all necessary fields to proceed with event registration",
    "event_form.name_label": "Event Name",
    "event_form.name_placeholder": "e.g. Mae Fah Luang Commencement Ceremony 2026",
    "event_form.name_help": "Specify a clear and descriptive name in Thai or English",
    "event_form.date_label": "Event Date",
    "event_form.date_help": "Scheduled date according to university academic calendar",
    "event_form.status_label": "Publication Status",
    "event_form.status_draft": "Draft - Hidden from students",
    "event_form.status_published": "Published - Visible to students",
    "event_form.status_archived": "Archived - Disabled",
    "event_form.timer_label": "Data Retention Timer (PDPA)",
    "event_form.timer_desc": "For privacy compliance, photos and facial embeddings are permanently purged after this duration",
    "event_form.days_unit": "Days",
    "event_form.custom_days": "Custom (Days):",
    "event_form.max_days": "(Maximum 30 days)",
    "event_form.btn_cancel": "Cancel",
    "event_form.btn_create": "Save & Create Event",
    "event_form.btn_save": "Save Changes",
    "event_form.btn_saving": "Saving changes...",
    "event_form.back": "Back to Dashboard",
    "event_form.next_steps_title": "Next steps after event creation:",
    "event_form.next_step1": "The event will appear in the administrative and photographer workspaces.",
    "event_form.next_step2": "Authorized photographers can immediately begin uploading event photographs.",
    "event_form.next_step3": "The AI service will process images and build facial embeddings for student face matching.",

    // Profile & Settings
    "profile.title": "Admin Account & Profile",
    "profile.subtitle": "Account credentials and access privilege scope for the central portal",
    "profile.details_title": "Personal Details",
    "profile.details_desc": "Information linked to your current authenticated session",
    "profile.scope_title": "Permission Scope",
    "profile.btn_dashboard": "Return to Dashboard",
    "profile.email_not_found": "No email address found",
    "profile.scope_desc_super": "You hold Super Administrator privileges: configure administrators, manage photographers, oversee campus events, moderate photo deletions, and monitor system health.",
    "profile.scope_desc_admin": "You hold Administrator privileges: manage events, approve removal/blur requests, and inspect AI confidence queues.",
    "settings.title": "Admin System Settings",
    "settings.subtitle": "Verify access privileges and central administrative configurations",
    "settings.session_title": "Admin Session Status",
    "settings.session_desc": "Current authentication session details and security state",
    "settings.signed_in_as": "Signed In As",
    "settings.session_active": "Admin session is authenticated and secure",
    "settings.user_roles_title": "Manage User Roles",
    "settings.user_roles_desc": "Assign photographers, update permissions, or manage user access",
    "settings.moderation_title": "Photo Removal Requests",
    "settings.moderation_desc": "Review and act on photo deletion or face blur requests",

    // User Settings & Privacy
    "user_settings.title": "Account & Settings",
    "user_settings.subtitle": "Manage profile information, notification preferences, and privacy consent (PDPA)",
    "user_settings.tab_account": "Account Profile",
    "user_settings.tab_privacy": "Privacy & Consent",
    "user_settings.profile_card_title": "Account Profile",
    "user_settings.profile_card_desc": "Details of the account currently authenticated in the system",
    "user_settings.full_name": "Full Name",
    "user_settings.email": "Email Address",
    "user_settings.role": "Account Role",
    "user_settings.sync_info": "This profile information is synced from your Google account. To update your name or photo, modify your Google account settings and sign out and back in to refresh it here.",
    "user_settings.line_title": "LINE Notifications",
    "user_settings.line_desc": "Receive real-time Flex Messages via LINE OA when we find new photos of you.",
    "user_settings.line_connected": "Connected",
    "user_settings.line_not_linked": "Not Linked",
    "user_settings.line_add_friend_title": "Before linking, please add our LINE OA as a friend first.",
    "user_settings.line_add_friend_desc": "Add via link:",
    "user_settings.line_search_id": "or search ID:",
    "user_settings.line_oa_warning": "If you do not add the OA first, LINE account linking and notifications will not work.",
    "user_settings.line_btn_unlink": "Unlink Account",
    "user_settings.line_btn_link": "Link LINE Account",
    "user_settings.line_status_linked": "Your LINE account is linked. You will receive notifications automatically when photos are matched.",
    "user_settings.email_title": "Email Notifications",
    "user_settings.email_desc": "Receive a summary email when we find photos of you at an event.",
    "user_settings.email_enabled": "Enabled",
    "user_settings.email_disabled": "Disabled",
    "user_settings.email_btn_enable": "Enable Email Notifications",
    "user_settings.email_btn_disable": "Disable Email Notifications",
    "user_settings.consent_card_title": "Consent Status",
    "user_settings.consent_card_desc": "Control your participation in the photo system and facial processing",
    "user_settings.consent_opted_in": "Opted In",
    "user_settings.consent_opted_out": "Opted Out",
    "user_settings.consent_active_desc": "Active: Your face is being identified in new event photos. You will be notified automatically when a match is found.",
    "user_settings.consent_passive_desc": "Passive: Your face is not being searched. No notifications will be sent and you will remain invisible to AI detection.",
    "user_settings.pref_card_title": "Update Preferences",
    "user_settings.pref_card_desc": "Manage your privacy configuration under PDPA regulations",
    "user_settings.withdraw_warning_title": "You are about to withdraw consent",
    "user_settings.withdraw_warning_1": "AI face matching and new match notifications will stop immediately.",
    "user_settings.withdraw_warning_2": "Your profile may no longer appear in automatic event discovery.",
    "user_settings.withdraw_warning_3": "After re-consenting, auto face matching can resume once you set a reference selfie again.",
    "user_settings.rights_title": "Your Privacy Rights",
    "user_settings.rights_1": "You can opt-out of face search at any time",
    "user_settings.rights_2": "Request removal or blur of photos featuring you",
    "user_settings.rights_3": "Download or delete your personal data permanently",
    "user_settings.btn_save": "Save Privacy Preferences",
    "user_settings.btn_saving": "Saving...",
    "user_settings.ci_title": "Consent Intelligence Actions",
    "user_settings.ci_export": "One-click Export Data",
    "user_settings.ci_delete": "One-click Full Delete",
    "user_settings.saved_success": "Privacy preferences saved successfully!",

    // Photographer Portal
    "portal.photographer_title": "PHOTOGRAPHER PORTAL",
    "portal.photographer_subtitle": "Event Photography Service",
    "nav.workspace": "Workspace",
    "nav.photographer_profile": "Profile",
    "photo.workspace_badge": "Event Photography Service",
    "photo.title": "Photographer Workspace",
    "photo.subtitle": "Upload, manage, and monitor event photo collections and engagement analytics",
    "photo.loading.title": "Loading photographer workspace...",
    "photo.loading.subtitle": "Preparing photographer workspace, events, and analytics.",
    "photo.auth.title": "Photographer Access Required",
    "photo.auth.desc": "Please sign in with a photographer account to access workspace and upload features.",
    "photo.auth.signin": "Sign In",
    "photo.metric.ready": "Ready for uploads",
    "photo.metric.no_events": "No events available",
    "photo.metric.processing": "Processing",
    "photo.metric.no_files_queue": "No files queued",
    "photo.step1_badge": "Step 1",
    "photo.step2_badge": "Step 2",
    "photo.tab.upload": "Upload Photos",
    "photo.tab.manage": "Manage Uploads",
    "photo.tab.analytics": "Analytics & Trends",
    "photo.upload.step1_title": "1. Select Target Event",
    "photo.upload.step1_desc": "Choose the registered event to upload photographs for",
    "photo.upload.select_placeholder": "-- Select Event --",
    "photo.upload.event_selected_prefix": "Photos will be assigned to event:",
    "photo.upload.event_select_prompt": "Please select an event before proceeding with file uploads",
    "photo.upload.no_event_selected": "No event selected",
    "photo.upload.event_label": "Event:",
    "photo.upload.step2_title": "2. Select Photo Files",
    "photo.upload.step2_desc": "Drag and drop or select images/folder from your computer",
    "photo.upload.dropzone_text": "Drag and drop photo files here",
    "photo.upload.dropzone_subtext": "Supports JPG, PNG, WEBP, and HEIC (automatic conversion)",
    "photo.upload.btn_select_files": "Select Files",
    "photo.upload.btn_select_folder": "Select Folder",
    "photo.upload.selected_summary": "Total files selected",
    "photo.upload.clear_all": "Clear List",
    "photo.upload.btn_upload": "Start Uploading Photos",
    "photo.upload.uploading": "Uploading & processing...",
    "photo.upload.step3_title": "Upload Progress & Status",
    "photo.upload.files_in_queue": "files in upload queue",
    "photo.upload.no_files": "No files selected yet",
    "photo.upload.queue_empty_guide": "Select files or a folder from the left box to add items",
    "photo.upload.btn_notify": "Notify Matched Users",
    "photo.upload.notifying": "Sending notifications...",
    "photo.upload.notify_desc": "Once event photos are uploaded, trigger matching notifications to students and attendees identified in the photos.",
    "photo.manage.title": "Uploaded Photo Catalog",
    "photo.manage.desc": "Review AI processing statuses, delete files, or retry failed items",
    "photo.manage.search_placeholder": "Search by event name or filename...",
    "photo.manage.total_photos": "photos in catalog",
    "photo.manage.col_preview": "Preview",
    "photo.manage.col_file": "Filename / Event",
    "photo.manage.col_date": "Upload Date",
    "photo.manage.col_status": "AI Status",
    "photo.manage.col_actions": "Actions",
    "photo.manage.empty": "No uploaded photos found in your account",
    "photo.manage.empty_guide": "Switch to the Upload tab to add event photos",
    "photo.manage.retry": "Retry",
    "photo.manage.delete": "Delete",
    "photo.status.completed": "Completed",
    "photo.status.processing": "Processing",
    "photo.status.failed": "Failed",
    "photo.status.pending": "Pending",
    "photo.analytics.loading": "Loading analytics data...",
    "photo.analytics.empty_events": "No event statistics available yet",
    "photo.analytics.metric.events": "Events Covered",
    "photo.analytics.metric.photos": "Total Photos",
    "photo.analytics.metric.views": "Total Photo Views",
    "photo.analytics.metric.downloads": "Total Downloads",
    "photo.analytics.chart_title": "Engagement Trends (Views & Downloads)",
    "photo.analytics.chart_desc": "Historical views and downloads for your uploaded event photos",
    "photo.analytics.7days": "Last 7 Days",
    "photo.analytics.14days": "Last 14 Days",
    "photo.analytics.views_label": "Views",
    "photo.analytics.downloads_label": "Downloads",
    "photo.analytics.event_stats_title": "Per-Event Breakdown",
    "photo.analytics.col_event": "Event Name",
    "photo.analytics.col_photos": "Photos",
    "photo.analytics.col_views": "Views",
    "photo.analytics.col_downloads": "Downloads",
    "photo.profile.title": "Settings",
    "photo.profile.subtitle": "Institutional photographer account credentials and activity statistics",
    "photo.profile.back": "Back to Workspace",
    "photo.profile.role_badge": "Authorized Photographer",
    "photo.profile.email_label": "Contact Email",
    "photo.profile.account_status": "Account Status",
    "photo.profile.active": "Active",
    "photo.profile.stat_total": "Total Photos Uploaded",
    "photo.profile.stat_completed": "AI Processed",
    "photo.profile.stat_processing": "Processing",
    "photo.profile.stat_events": "Events Covered",
    "photo.profile.metrics_title": "Activity Metrics",
    "photo.profile.guidelines_title": "Photographer Guidelines & Operational Standards",
    "photo.profile.guide1_title": "Target Event Accuracy",
    "photo.profile.guide1_desc": "Always select the correct event before uploading to ensure accurate AI indexing and face matching.",
    "photo.profile.guide2_title": "Image File Quality",
    "photo.profile.guide2_desc": "Supports JPG, PNG, and HEIC (auto-converted), up to 15MB per image file.",
    "photo.profile.guide3_title": "Notify Matched Attendees",
    "photo.profile.guide3_desc": "After finishing photo uploads, click Notify to send matched photo summaries to students.",
    "photo.profile.guide4_title": "PDPA Privacy Compliance",
    "photo.profile.guide4_desc": "Upload logs and photo records are strictly handled in accordance with university PDPA policies.",

    // Privacy Policy Page
    "privacy.badge": "Transparency & PDPA Standards",
    "privacy.title": "Privacy & Data Handling",
    "privacy.subtitle": "At PhotoFinder, your privacy is our highest priority. We use AI facial recognition solely to help you find your campus memories. We believe in complete transparency, zero commercial data exploitation, and putting you in total control of your data.",
    "privacy.last_updated": "Last updated:",
    "privacy.nav.back": "Back to Portal",
    "privacy.nav.settings": "Privacy Settings",
    "privacy.pill.pdpa": "PDPA Compliant",
    "privacy.pill.retention": "30-Day Auto-Purge",
    "privacy.pill.vector": "512-D Face Vectors",
    "privacy.pill.control": "100% User Control",
    "privacy.jump.lifecycle": "AI Data Lifecycle",
    "privacy.jump.guarantees": "Our Guarantees",
    "privacy.jump.retention": "30-Day Auto-Purge",
    "privacy.jump.rights": "Your PDPA Rights",
    "privacy.jump.security": "Security Architecture",
    "privacy.jump.faq": "FAQ",
    "privacy.lifecycle.title": "1. AI Face Processing Lifecycle",
    "privacy.lifecycle.desc": "Understand how our system converts photographs into mathematical coordinates without storing permanent biometric images.",
    "privacy.step1.title": "1. Photo Ingestion",
    "privacy.step1.desc": "Photographers upload event galleries, or students upload an optional reference selfie for self-matching.",
    "privacy.step2.title": "2. 512-D Vectorization",
    "privacy.step2.desc": "AI extracts facial landmarks into an encrypted 512-dimensional numerical vector, not raw image templates.",
    "privacy.step3.title": "3. Cosine Matching",
    "privacy.step3.desc": "Calculates mathematical distance in memory to match faces that exceed high confidence thresholds.",
    "privacy.step4.title": "4. 30-Day Auto-Purge",
    "privacy.step4.desc": "All event images, facial embeddings, and temporary caches are permanently expunged after 30 days.",
    "privacy.do_dont.title": "2. Guarantees & Strict Prohibitions",
    "privacy.do_dont.desc": "Complete institutional transparency: what we pledge to protect you, and what we strictly forbid.",
    "privacy.dos.title": "What We Guarantee (Our Promise)",
    "privacy.dos.item1": "Process facial vectors strictly to help you locate event photos you consent to find.",
    "privacy.dos.item2": "Store reference selfies in private, encrypted vaults, deletable with 1-click anytime.",
    "privacy.dos.item3": "Permanently purge all event photos and vector data after 30 days automatically.",
    "privacy.dos.item4": "Provide instant 'Request Removal' and face-blur moderation tools directly on every photo.",
    "privacy.dos.item5": "Support self-service full data export (JSON) and instant permanent profile deletion.",
    "privacy.donts.title": "What We NEVER Do (Strictly Forbidden)",
    "privacy.donts.item1": "NEVER sell, rent, monetize, or trade your personal data or photos to third parties.",
    "privacy.donts.item2": "NEVER use facial recognition for attendance tracking, classroom grading, or surveillance.",
    "privacy.donts.item3": "NEVER use student photographs to train commercial external AI models.",
    "privacy.donts.item4": "NEVER archive or retain campus event galleries beyond the 30-day lifecycle.",
    "privacy.donts.item5": "NEVER allow unauthenticated web crawlers or unauthorized parties to index event photos.",
    "privacy.retention.title": "3. Data Retention & 30-Day Auto-Purge",
    "privacy.retention.desc": "Data minimization and automated purging compliant with international PDPA benchmarks.",
    "privacy.retention.events_title": "Campus Event Photos (Strictly Temporary 30 Days)",
    "privacy.retention.events_desc": "All photos uploaded to campus events expire within 30 days of publishing. Our automated worker deletes original assets from Cloudinary CDN and flushes all PostgreSQL facial embeddings irreversibly. We do not archive event photos long-term.",
    "privacy.retention.selfie_title": "Your Reference Selfie (Under Your Absolute Control)",
    "privacy.retention.selfie_desc": "The reference selfie you upload to find yourself is kept securely in your private profile so you don't need to re-upload for every event. It remains until you choose to click 'Reset Profile' or withdraw consent in Settings.",
    "privacy.retention.logs_title": "System Security & Audit Logs (90 Days)",
    "privacy.retention.logs_desc": "Anonymized access logs are retained strictly for security diagnostics and regulatory compliance, rotated and cleared every 90 days.",
    "privacy.rights.title": "4. Your Rights Under PDPA",
    "privacy.rights.desc": "Under Thailand's Personal Data Protection Act (B.E. 2562), you are endowed with complete data subject rights:",
    "privacy.rights.withdraw_title": "Right to Withdraw Consent",
    "privacy.rights.withdraw_desc": "You can switch off AI face matching at any time in Settings. Once disabled, no new event photos will scan for your face.",
    "privacy.rights.erasure_title": "Right to Erasure (Right to be Forgotten)",
    "privacy.rights.erasure_desc": "If you find a photo you do not want in the system, click 'Request Removal' or 'Request Blur'. Admins review and purge or blur it promptly.",
    "privacy.rights.portability_title": "Right to Data Portability",
    "privacy.rights.portability_desc": "Use 'One-Click Export Data' in Settings to receive a structured JSON copy of all personal profile and match records.",
    "privacy.rights.wipe_title": "One-Click Full Delete",
    "privacy.rights.wipe_desc": "Completely erase your profile, reference selfie, and all mathematical embeddings permanently in one click.",
    "privacy.rights.btn_settings": "Open Privacy Settings",
    "privacy.security.title": "5. Security & Technical Architecture",
    "privacy.security.desc": "Institutional-grade technical safeguards protecting user confidentiality and platform integrity.",
    "privacy.security.item1_title": "End-to-End Encryption",
    "privacy.security.item1_desc": "All network traffic is secured via TLS 1.3, with sensitive database fields and vector metadata encrypted with AES-256.",
    "privacy.security.item2_title": "Row-Level Isolation",
    "privacy.security.item2_desc": "PostgreSQL Row-Level Security ensures users can only query their own matched photos and records.",
    "privacy.security.item3_title": "Signed CDN URLs",
    "privacy.security.item3_desc": "Cloudinary assets use cryptographically signed URLs with short expiration tokens to prevent hotlinking or scraping.",
    "privacy.security.item4_title": "Sandboxed AI Inference",
    "privacy.security.item4_desc": "Facial processing runs in an isolated CPU container with zero telemetry leaked to external third parties or public APIs.",
    "privacy.faq.title": "6. Frequently Asked Questions",
    "privacy.faq.desc": "Common questions regarding student privacy, photo rights, and system safety.",
    "privacy.faq.q1": "Do I have to upload a selfie to view campus event photos?",
    "privacy.faq.a1": "No. You can freely browse campus event galleries and download photos manually without uploading a selfie. The selfie is strictly optional for automated face matching.",
    "privacy.faq.q2": "Are event photos really deleted permanently after 30 days?",
    "privacy.faq.a2": "Yes, absolutely. An automated daily cron job permanently removes expired event photos from Cloudinary CDN and wipes all associated face embeddings from the database.",
    "privacy.faq.q3": "Can another student or stranger use my photo to search for me?",
    "privacy.faq.a3": "No. Searching requires signing in with an authenticated university account, and Identity Guard prevents unauthorized identity impersonation.",
    "privacy.faq.q4": "What should I do if I find an unwanted photo of myself?",
    "privacy.faq.a4": "Simply click on the photo and select 'Request Removal' or 'Request Blur'. Administrators review and approve deletion or blurring promptly.",
    "privacy.faq.q5": "Can 512-D vectors be reverse-engineered back into my original face photo?",
    "privacy.faq.a5": "No. Embeddings are one-way mathematical coordinate representations used for distance calculation. They cannot be reconstructed back into photographic face images.",
    "privacy.contact.title": "Data Protection Officer (DPO Contact)",
    "privacy.contact.desc": "If you have questions, feedback, or wish to exercise statutory PDPA rights, please contact our Data Protection Officer.",
    "privacy.contact.univ": "Mae Fah Luang University (MFU)",
    "privacy.contact.addr": "333 Moo 1, Thasud, Mueang, Chiang Rai 57100 Thailand",
    "privacy.contact.email_label": "Email:",
    "privacy.contact.email_val": "dpo@mfu.ac.th, photofinder-support@mfu.ac.th",
    "privacy.contact.hours_label": "Office Hours:",
    "privacy.contact.hours_val": "Monday - Friday 08:00 - 16:00 (ICT, excluding public holidays)",

    // Photo Detail Modal
    "detail.photo_moment": "Photo moment",
    "detail.match": "match",
    "detail.saved": "Saved",
    "detail.favorite": "Favorite",
    "detail.share": "Share",
    "detail.download_original": "Download original",
    "detail.share_to": "Share to",
    "detail.request_removal": "Request Removal",
    "detail.removal_title": "Request Photo Removal",
    "detail.removal_desc": "Our team will review your request within 24 hours. You'll receive an email confirmation.",
    "detail.group_photos_label": "Group Photos:",
    "detail.group_photos_desc": "If this photo contains multiple people, our team may choose to apply a mosaic pixelation to your face instead of deleting the entire photo. This ensures your privacy is protected while preserving the memory for others.",
    "detail.reason_label": "Reason for Removal",
    "detail.reason_placeholder": "Please explain why you want this photo removed",
    "detail.submitting": "Submitting...",
    "detail.submit_request": "Submit Request",
    "detail.cancel": "Cancel",
    "detail.zoom_in": "Zoom in",
    "detail.zoom_out": "Zoom out",
    "detail.enter_fullscreen": "Enter fullscreen",
    "detail.exit_fullscreen": "Exit fullscreen",
    "detail.close": "Close",
    "detail.share_error": "Unable to open share right now. Please try again.",
    "detail.favorite_remove_error": "Unable to remove this photo from Favorites right now.",
    "detail.favorite_add_error": "Unable to add this photo to Favorites right now.",
    "detail.favorite_update_error": "Unable to update Favorites right now.",
    "detail.fullscreen_error": "Fullscreen is not available on this browser.",
    "detail.reason_required": "Please provide a reason for removal",
    "detail.removal_failed": "Failed to submit removal request. Please try again.",
    "detail.removal_success": "Removal request submitted successfully. Our team will review it within 24 hours.",
    "detail.error_generic": "An error occurred. Please try again.",
  },
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "th",
  setLang: () => {},
  t: (key: string) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>("th")

  useEffect(() => {
    const saved = localStorage.getItem("app_lang") as Language | null
    if (saved === "th" || saved === "en") {
      setLangState(saved)
    }
  }, [])

  const setLang = (newLang: Language) => {
    setLangState(newLang)
    localStorage.setItem("app_lang", newLang)
    if (typeof window !== "undefined") {
      window.dispatchEvent(new Event("languagechange"))
    }
  }

  useEffect(() => {
    const handleLangChange = () => {
      const current = localStorage.getItem("app_lang") as Language | null
      if (current && (current === "th" || current === "en") && current !== lang) {
        setLangState(current)
      }
    }
    window.addEventListener("languagechange", handleLangChange)
    return () => window.removeEventListener("languagechange", handleLangChange)
  }, [lang])

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations["th"]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
